import assert from 'node:assert/strict';import zlib from 'node:zlib';import {command,sha,validatePayload} from './reference.mjs';
const base=process.env.DOOM_T82_BASE_URL;if(!base)throw Error('DOOM_T82_BASE_URL is required; direct API checks never skip');
const origin=new URL(base).origin,requests=[];
async function post(name,body,expectOk=true){const stem=name.replace(/^\//,'').replace(/\/$/,'');const root=base.endsWith('/')?base:`${base}/`;let r,url;for(const path of [stem.toUpperCase(),`${stem.toLowerCase()}/`]){url=new URL(path,root);assert.equal(url.origin,origin);assert.equal(url.protocol,process.env.DOOM_T82_ALLOW_HTTP==='1'?'http:':'https:');r=await fetch(url,{method:'POST',headers:{'content-type':'application/json','accept':'application/json'},body:JSON.stringify(body),redirect:'manual'});if(r.status!==404)break}requests.push(url.pathname);assert.equal(r.headers.get('location'),null,'redirect forbidden');const text=await r.text();if(expectOk)assert.equal(r.status,200,`${name}: ${text}`);else{assert.ok(r.status>=400,`${name}: deterministic client error`);return {status:r.status,text}}assert.match(r.headers.get('content-type')||'',/^application\/json\b/i);return JSON.parse(text)}
function value(o,k){return o[k]??o[k.toUpperCase()]??o.items?.[0]?.[k]??o.items?.[0]?.[k.toUpperCase()]}
function payload(o){const encoded=value(o,'p_payload');assert.equal(typeof encoded,'string');let b=Buffer.from(encoded,'base64');if(b[0]===0x1f&&b[1]===0x8b){b=zlib.gunzipSync(b);const p=JSON.parse(b.toString('utf8'));return {...p,pixels:validatePayload(p)}}assert.equal(b.subarray(0,4).toString(),'DMF3');const tic=b.readInt32BE(4),complete=b[9],state_sha=b.subarray(10,74).toString('ascii'),frame_sha=b.subarray(74,138).toString('ascii'),audioBytes=b.readUInt16BE(138),audio=JSON.parse(b.subarray(140,140+audioBytes).toString('ascii')),transport=b.subarray(140+audioBytes);assert.equal(transport.length,64000);assert.match(state_sha,/^[0-9a-f]{64}$/);assert.match(frame_sha,/^[0-9a-f]{64}$/);const pixels=Buffer.alloc(64000);for(let x=0;x<320;x++)for(let y=0;y<200;y++)pixels[y*320+x]=transport[x*200+y];assert.equal(sha(pixels),frame_sha);return {v:3,tic,w:320,h:200,mode:b[8]===1?'DEAD':complete===1?'INTERMISSION':'GAME',state_sha,frame_sha,audio,complete,pixels}}
const ng=await post('new_game',{p_skill:3}),session=value(ng,'p_session');assert.match(session,/^[0-9a-f]{32}$/);const spawn=payload(ng),spawnPixels=spawn.pixels;assert.equal(spawn.tic,0);assert.equal(spawn.mode,'GAME');
let seq=1;const step=async patch=>{const out=await post('step',{p_session:session,p_commands:JSON.stringify({v:1,commands:[command(seq++,patch)]})});return payload(out)};
const paused=await step({pause:1}),held=await step({forward:1,strafe:1,run:1,fire:1,use:1});assert.equal(paused.mode,'GAME');assert.notEqual(paused.frame_sha,spawn.frame_sha,'pause overlay must be visible');assert.notEqual(held.state_sha,paused.state_sha,'logical command history advances while paused');assert.equal(held.tic,paused.tic+1,'paused command still owns one durable tic');const unpaused=await step({pause:1});assert.notEqual(unpaused.frame_sha,held.frame_sha);
const normalMap=await step({automap:1});const fullMap=await step({cheat:'FULLMAP'});assert.notEqual(fullMap.frame_sha,normalMap.frame_sha);const normalAgain=await step({cheat:'FULLMAP'});assert.notEqual(normalAgain.frame_sha,fullMap.frame_sha);
for(const cheat of ['GOD','GOD','ALL','ALL','NOCLIP','NOCLIP'])await step({cheat});
const saved=await post('save_game',{p_session:session,p_slot:3}),savedSha=value(saved,'p_state_sha');assert.match(savedSha,/^[0-9a-f]{64}$/);const branch=[];for(const p of [{turn:1},{forward:1,run:1},{fire:1},{turn:-1,strafe:1,use:1}])branch.push(await step(p));const loaded=payload(await post('load_game',{p_session:session,p_slot:3}));assert.equal(loaded.state_sha,savedSha);const branch2=[];for(const p of [{turn:1},{forward:1,run:1},{fire:1},{turn:-1,strafe:1,use:1}])branch2.push(await step(p));assert.deepEqual(branch2.map(x=>[x.state_sha,x.frame_sha,x.audio]),branch.map(x=>[x.state_sha,x.frame_sha,x.audio]));
const replayFrom=1,replayTo=branch2.at(-1).tic,replayStart=await post('start_replay',{p_session:session,p_from_tic:replayFrom,p_to_tic:replayTo}),replay=value(replayStart,'p_replay_id');assert.match(replay,/^[0-9a-f]{32}$/);let last;for(let i=replayFrom;i<=replayTo;i++)last=payload(await post('step_replay',{p_replay_id:replay}));assert.ok(last.complete===0||last.complete===1);
const beforeBad=branch2.at(-1);const bad=await post('step',{p_session:session,p_commands:JSON.stringify({v:1,commands:[command(seq,{turn:2})]})},false);assert.ok(bad.status>=400);const retry=await step({});assert.equal(retry.tic,beforeBad.tic+1,'failed command did not mutate frontier');
assert.ok(requests.every(p=>/\/doom_api\/(?:new_game|step|save_game|load_game|start_replay|step_replay)\/?$/i.test(p)));assert.equal(spawnPixels.length,64000);process.stdout.write(`PASS T8.2-DIRECT-API (${requests.length} exact same-origin workflow requests; terminal ${sha(last.state_sha)})\n`);
