import crypto from 'node:crypto';
export const KEYS=['seq','turn','forward','strafe','run','fire','use','weapon','pause','automap','menu','cheat'];
export const MENUS=new Set(['NONE','OPEN','DOWN','UP','SELECT','BACK','RESTART']);
export const CHEATS=/^(?:|GOD|ALL|NOCLIP|FULLMAP|REWIND:(?:0|[1-9][0-9]*))$/;
export const sha=x=>crypto.createHash('sha256').update(typeof x==='string'?x:ArrayBuffer.isView(x)?x:JSON.stringify(x)).digest('hex');
export function command(seq,patch={}){return {seq,turn:0,forward:0,strafe:0,run:0,fire:0,use:0,weapon:0,pause:0,automap:0,menu:'NONE',cheat:'',...patch}}
export function validateCommand(c,expectedSeq){
  if(!c||typeof c!=='object'||Array.isArray(c)||Object.keys(c).sort().join()!=[...KEYS].sort().join())throw Error('exact keys');
  if(c.seq!==expectedSeq)throw Error('sequence');
  for(const k of ['seq','turn','forward','strafe','run','fire','use','weapon','pause','automap'])if(!Number.isInteger(c[k]))throw Error(`integer ${k}`);
  if(![-1,0,1].includes(c.turn)||![-1,0,1].includes(c.forward)||![-1,0,1].includes(c.strafe))throw Error('axis range');
  for(const k of ['run','fire','use','pause','automap'])if(![0,1].includes(c[k]))throw Error(`boolean ${k}`);
  if(c.weapon<0||c.weapon>9||!MENUS.has(c.menu)||!CHEATS.test(c.cheat)||c.menu.length>32||c.cheat.length>32)throw Error('control');return c;
}
export function validateBatch(body,frontier=0){if(body?.v!==1||!Array.isArray(body.commands)||body.commands.length<1||body.commands.length>4||Object.keys(body).sort().join()!=='commands,v')throw Error('envelope');body.commands.forEach((c,i)=>validateCommand(c,frontier+i+1));return body}
export function expandColumns(cols){if(!Array.isArray(cols)||cols.length!==320)throw Error('columns');const out=new Uint8Array(64000);for(let x=0;x<320;x++){let y=0;for(const r of cols[x]){if(!Array.isArray(r)||r.length!==3||r.some(v=>!Number.isInteger(v))||r[0]!==y||r[1]<=0||r[2]<0||r[2]>255||y+r[1]>200)throw Error('run');out.fill(r[2],x*200+y,x*200+y+r[1]);y+=r[1]}if(y!==200)throw Error('coverage')}return out}
export function validatePayload(p){if(!p||Object.keys(p).sort().join()!==['audio','cols','complete','frame_sha','h','mode','state_sha','tic','v','w'].sort().join())throw Error('payload keys');if(p.v!==1||p.w!==320||p.h!==200||!Number.isInteger(p.tic)||p.tic<0||![0,1].includes(p.complete)||!['GAME','MENU','AUTOMAP','DEAD','INTERMISSION'].includes(p.mode))throw Error('payload scalar');if(!/^[0-9a-f]{64}$/.test(p.state_sha)||!/[0-9a-f]{64}/.test(p.frame_sha))throw Error('hash');const pixels=expandColumns(p.cols);if(sha(pixels)!==p.frame_sha)throw Error('frame hash');for(let i=0;i<p.audio.length;i++){const a=p.audio[i];if(!Array.isArray(a)||a.length!==5||a[0]!==p.tic||a[1]!==i||typeof a[2]!=='string'||!Number.isInteger(a[3])||!Number.isInteger(a[4]))throw Error('audio tuple')}return pixels}
export function modelControls(sequence,mutation={}){let s={paused:0,menu:'NONE',selection:0,automap:'OFF',god:0,noclip:0,fullmap:0,tic:0,gameTicks:0,rng:7,seq:0,lineage:0};const snapshots=[];for(const c0 of sequence){const c=validateCommand(c0,s.seq+1);s={...s,tic:s.tic+1,seq:c.seq};if(c.pause)s.paused=1-s.paused;if(c.menu!=='NONE'){if(c.menu==='OPEN'){s.menu='MAIN';s.selection=0}else if(c.menu==='DOWN'&&s.menu==='MAIN')s.selection=mutation.menuFixed?0:(s.selection+1)%3;else if(c.menu==='UP'&&s.menu==='MAIN')s.selection=(s.selection+2)%3;else if(c.menu==='SELECT'&&s.menu==='MAIN')s.menu=s.selection===1?'SKILL':'MAIN';else if(c.menu==='BACK')s.menu='NONE';else if(c.menu==='RESTART')s={...s,paused:0,menu:'NONE',automap:'OFF',tic:0,gameTicks:0,rng:7,lineage:s.lineage+1};}
    if(c.automap){s.automap=s.automap==='OFF'?'NORMAL':'OFF';s.fullmap=0}if(c.cheat==='GOD')s.god=mutation.godOneWay?1:1-s.god;if(c.cheat==='NOCLIP')s.noclip=1-s.noclip;if(c.cheat==='FULLMAP'){s.fullmap=1-s.fullmap;s.automap=s.fullmap?'FULL':'NORMAL'}if(c.cheat.startsWith('REWIND:')){const t=Number(c.cheat.slice(7));if(t>s.tic-1)throw Error('future rewind');s.tic=t;s.lineage++}const gameplay=!s.paused&&s.menu==='NONE'&&c.menu==='NONE';if(gameplay)s.gameTicks++;if(s.paused&&mutation.pauseAdvancesRng)s.rng=(s.rng*17+3)%256;else if(gameplay)s.rng=(s.rng*17+3)%256;snapshots.push({...s})}return snapshots}
export function expectedNetwork(f){return f.network.paths.map(path=>`POST ${path} application/json`)}
