import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';import path from 'node:path';import {CHEATS,KEYS,command,expectedNetwork,expandColumns,modelControls,sha,validateBatch} from './reference.mjs';
const load=n=>JSON.parse(fs.readFileSync(new URL(n,import.meta.url))),f=load('./fixtures.json'),ids=load('./test-ids.json'),mut=load('./mutation-specs.json');let n=0;const eq=(a,b,s)=>{assert.deepEqual(a,b,s);n++},ok=(x,s)=>{assert.ok(x,s);n++};
eq(f.map,'E1M1','map');eq(f.skills.accepted,[1,2,3,4,5],'skill domain');eq(f.commandKeys,KEYS,'exact command keys');eq(f.cheats.map(x=>x.code),['GOD','ALL','NOCLIP','FULLMAP'],'required cheats');eq(f.rewindEncoding.pattern,'REWIND:<tic>','public rewind encoding');ok(CHEATS.test('REWIND:0')&&CHEATS.test('REWIND:123')&&!CHEATS.test('REWIND:-1')&&!CHEATS.test('rewind:3'),'rewind grammar');eq(f.payload.w*f.payload.h,64000,'frame area');eq(f.network.paths.length,7,'fixed public endpoints');ok(expectedNetwork(f).every(x=>x.startsWith('POST ')&&x.endsWith(' application/json')),'network tuple');eq(new Set(f.errors).size,f.errors.length,'negative cases unique');
eq(ids.tests.length,28,'test ids');eq(new Set(ids.tests.map(x=>x.id)).size,28,'unique test ids');eq(ids.tests.reduce((a,x)=>a+x.assertions,0),ids.declaredAssertions,'declared assertion sum');ok(ids.tests.every(x=>/^T82-[A-Z0-9-]+$/.test(x.id)&&x.intent.length>=120),'strong stable intents');eq(mut.mutations.length,24,'mutation count');eq(new Set(mut.mutations.map(x=>x.id)).size,24,'unique mutation ids');ok(mut.mutations.every(x=>ids.tests.some(t=>t.id===x.killedBy)&&x.change.length>=65&&x.reason.length>=80),'focused mutation witnesses');
const pause=f.pause.commands.map(x=>command(x.seq,x));pause.forEach((c,i)=>validateBatch({v:1,commands:[c]},i));const ps=modelControls(pause);eq(ps.map(x=>x.paused),[1,1,0],'pause transitions');eq(ps[1].gameTicks,ps[0].gameTicks,'pause freezes gameplay');eq(ps[1].rng,ps[0].rng,'pause freezes rng');ok(ps[2].gameTicks>ps[1].gameTicks,'unpause resumes gameplay');
const menu=f.menu.commands.map((menu,i)=>command(i+1,{menu})),ms=modelControls(menu);eq(ms.map(x=>x.menu==='NONE'?'NONE':`${x.menu}:${x.menu==='MAIN'?x.selection:0}`),f.menu.states,'exact menu states');eq(new Set(ms.map(x=>x.gameTicks)).size,1,'menu gameplay frozen');
const amap=f.automap.commands.map((x,i)=>command(i+1,x)),as=modelControls(amap);eq(as.map(x=>x.automap),f.automap.states,'automap transitions');const toggles=modelControls([command(1,{cheat:'GOD'}),command(2,{cheat:'GOD'}),command(3,{cheat:'NOCLIP'}),command(4,{cheat:'NOCLIP'})]);eq(toggles.map(x=>[x.god,x.noclip]),[[1,0],[0,0],[0,1],[0,0]],'reversible cheat toggles');assert.throws(()=>validateBatch({v:1,commands:[command(2)]},0));n++;assert.throws(()=>validateBatch({v:1,commands:[{...command(1),extra:1}]},0));n++;assert.throws(()=>validateBatch({v:1,commands:[command(1,{cheat:'god'})]},0));n++;
const cols=Array.from({length:320},(_,x)=>[[0,100,x%256],[100,100,(x+1)%256]]),pixels=expandColumns(cols);eq(pixels.length,64000,'RLE expansion');eq(sha(pixels),crypto.createHash('sha256').update(pixels).digest('hex'),'byte hash');
const root=path.resolve(import.meta.dirname,'../..'),inherited=[
 ['evaluator/integrity.json','2699e0e0f6e93593d8172ea19a048d2ad6ebabb57aef2604a81782c25f2882a3'],
 ['evaluator/integrity.pending-T6.4.json','49df1e47ef6612dbaf50671f7d362c5f6546d40818c588e9b69d053d1d007081'],
 ['evaluator/integrity.pending-T7.1.json','45be1db5dea63fc4291851ac4e692e9a66bd903096b35bf8b2379a190503f30e'],
 ['evaluator/integrity.pending-T7.2.json','764dda2fbf89bcb02511e6ffc9e3ba877757cfedb9b2d5a8981bb37b444e82e5'],
 ['evaluator/integrity.pending-T7.3.json','6267d2dcce1bf52136309c7bda6641325ac69ce1e95b506bf4b3812bd89e9da6'],
 ['evaluator/integrity.pending-T8.1.json','9d397f036967aa0a62b61177a7d089957f0c3c6e5d6a34c0b3da310c75305b95']
];for(const [p,want] of inherited)eq(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex'),want,`${p} inherited identity`);
process.stdout.write(`PASS T8.2-EVAL-SELF-CHECK (${n}/${n} fixture-contract assertions)\n`);
