import crypto from 'node:crypto';
const clone=x=>structuredClone(x),sgn=x=>x<0?-1:x>0?1:0;
export function reachable(graph,source,target,opt={}){const q=[source],seen=new Set(q);while(q.length){const a=q.shift();if(a===target)return true;for(const e of graph.edges){if(!e.includes(a))continue;if(!opt.ignoreSoundBlocks&&graph.blocked.some(b=>b[0]===e[0]&&b[1]===e[1]))continue;const b=e[0]===a?e[1]:e[0];if(!seen.has(b)){seen.add(b);q.push(b)}}}return false}
export function visible(los,from,to,opt={}){if(!opt.ignoreReject&&los.rejectPairs.some(p=>p[0]===from&&p[1]===to))return false;return !los.intercepts.some(i=>i.distance<los.targetDistance&&i.blocking&&!opt.ignoreIntercepts)}
export function chooseDirection(m,p,blocked=[],opt={}){const sx=sgn(p.x-m.x),sy=sgn(p.y-m.y),choices=opt.reverseDirections?[[0,sy],[sx,0],[sx,sy]]:[[sx,sy],[sx,0],[0,sy]];return choices.find(([x,y])=>!blocked.some(b=>b[0]===x&&b[1]===y))??[0,0]}
export function wake(s,f,opt={}){s=clone(s);const heard=reachable(f.soundGraph,s.monster.sector,s.player.sector,opt),seen=visible(f.los,s.monster.sector,s.player.sector,opt);if(heard||seen){s.monster.target=s.player.id;s.monster.state='CHASE';s.monster.stateTics=3;s.events.push({tic:s.tic,type:'MONSTER_WAKE',actor:s.monster.id,reason:seen?'SEEN':'HEARD'})}return s}
export function advance(s,f,opt={}){s=clone(s);const d=f.defs[s.monster.type];s.tic++;if(s.monster.dead)return s;if(--s.monster.stateTics>0)return s;const st=f.states.find(x=>x.id===s.monster.state);s.monster.state=opt.skipNext?s.monster.state:st.next;s.monster.stateTics=f.states.find(x=>x.id===s.monster.state).tics;if(s.monster.state==='CHASE'){const dist=Math.hypot(s.player.x-s.monster.x,s.player.y-s.monster.y);if(dist<=d.meleeRange)s.monster.state='MELEE';else if(d.attack==='PROJECTILE')s.monster.state='MISSILE';else if(d.attack==='HITSCAN')s.monster.state='HITSCAN';else {const dir=chooseDirection(s.monster,s.player,opt.blocked??[],opt);s.monster.dir=dir;s.monster.x+=dir[0]*d.speed;s.monster.y+=dir[1]*d.speed}}return s}
export function attack(s,f,opt={}){s=clone(s);const d=f.defs[s.monster.type],roll=f.rng[s.rngCursor++%f.rng.length],damage=d.damageBase*(1+(roll%d.damageDice));if(s.monster.state==='MELEE'){if(Math.hypot(s.player.x-s.monster.x,s.player.y-s.monster.y)<=d.meleeRange&&visible(f.los,s.monster.sector,s.player.sector,opt)){s.player.health=Math.max(0,s.player.health-damage);s.events.push({tic:s.tic,type:'MELEE_HIT',actor:s.monster.id,damage})}}else if(s.monster.state==='HITSCAN'){if(visible(f.los,s.monster.sector,s.player.sector,opt)){s.player.health=Math.max(0,s.player.health-damage);s.events.push({tic:s.tic,type:'HITSCAN_HIT',actor:s.monster.id,damage})}}else if(s.monster.state==='MISSILE'){s.projectiles.push({id:s.monster.id*1000+s.tic,owner:s.monster.id,type:d.projectile,x:s.monster.x,y:s.monster.y,target:s.player.id});s.events.push({tic:s.tic,type:'PROJECTILE_SPAWN',actor:s.monster.id})}return s}
export function hurt(s,f,damage,opt={}){s=clone(s);const d=f.defs[s.monster.type];s.monster.health-=damage;if(s.monster.health<=0){s.monster.health=0;s.monster.dead=true;s.monster.state='DEATH';s.monster.stateTics=5;s.events.push({tic:s.tic,type:'MONSTER_DEATH',actor:s.monster.id});if(d.drop!=null&&!opt.noDrop)s.drops.push({owner:s.monster.id,type:d.drop,x:s.monster.x,y:s.monster.y})}else{const roll=f.rng[s.rngCursor++%f.rng.length];if((opt.alwaysPain||roll<d.painChance)&&!opt.noPain){s.monster.state='PAIN';s.monster.stateTics=2;s.events.push({tic:s.tic,type:'MONSTER_PAIN',actor:s.monster.id})}}return s}
export const digest=s=>crypto.createHash('sha256').update(JSON.stringify(s)).digest('hex');
