import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';
const root=path.resolve(import.meta.dirname,'../..'),monster=path.join(root,'sql/sim/060_monsters.sql'),tic=path.join(root,'sql/sim/tic/010_tic_transaction.sql');
export function audit(c,t){const s=c.toUpperCase(),tx=t.toUpperCase();for(const x of ['CREATE OR REPLACE PACKAGE DOOM_MONSTERS','AUTHID DEFINER','PROCEDURE ADVANCE','DOOM_MONSTER_DEF','DOOM_STATE_DEF','DOOM_RNG_VALUE','DOOM_REJECT_BYTE','DOOM_MAP_LINEDEF','DOOM_MAP_SIDEDEF','GAME_SESSIONS','PLAYERS','MOBJS','GAME_EVENTS','TARGET_MOBJ_ID','STATE_TICS','NEXT_STATE_ID','ORDER BY'])assert.ok(s.includes(x),`required monster token absent: ${x}`);
 assert.ok(tx.includes('DOOM_MONSTERS.ADVANCE'),'tic transaction does not delegate monster advancement');
 assert.ok(/DOOM_STATE_DEF[\s\S]{0,1200}(JOIN|MERGE)[\s\S]{0,1200}(NEXT_STATE_ID|STATE_TICS)/.test(s),'relational state advancement join absent');
 assert.ok(/DOOM_MONSTER_DEF[\s\S]{0,1400}(JOIN|SELECT)[\s\S]{0,1400}(ATTACK_KIND|PAIN_CHANCE|DROP_THING_TYPE)/.test(s),'relational monster behavior join absent');
 assert.ok(/DOOM_REJECT_BYTE[\s\S]{0,1200}(BITAND|POWER|REJECT)/.test(s),'REJECT negative filter absent');
 assert.ok(/(CONNECT BY|RECURSIVE|BREADTH FIRST|SEARCH BREADTH|SECTOR_GRAPH|SOUND_REACH)[\s\S]{0,1600}(SOUND_BLOCK|VISITED|CYCLE)/.test(s),'bounded graph sound reachability absent');
 assert.ok(/(DOOM_R1_RAYS|INTERSECT)[\s\S]{0,1600}(LINEDEF|NUMERATOR|DENOMINATOR|DISTANCE)[\s\S]{0,1000}(ORDER BY|ROW_NUMBER)/.test(s),'exact ordered LOS intercept path absent');
 assert.ok(/(MOVE_DIRECTION|DIRECTION)[\s\S]{0,1300}(COLLISION|BLOCK|RADIUS)[\s\S]{0,900}ORDER BY/.test(s),'deterministic direction collision path absent');
 assert.ok(!/\b(COMMIT|ROLLBACK|PRAGMA\s+AUTONOMOUS_TRANSACTION)\b/.test(s),'monster package owns transaction boundary');assert.ok(!/EXECUTE\s+IMMEDIATE|DBMS_SQL/.test(s),'dynamic SQL forbidden');assert.ok(!/DBMS_RANDOM|SYSDATE|SYSTIMESTAMP|CURRENT_TIMESTAMP/.test(s),'host random or wall-clock gameplay forbidden');
 for(const bad of ['EVALUATOR/','FIXTURES.JSON','MUTATION-SPECS','REPORTS/','PLAYWRIGHT','CALL_STACK','FORMAT_CALL_STACK','V$PROCESS','T72-','THING_TYPE IN (9','WHEN 9 THEN','WHEN 58 THEN','WHEN 3001 THEN','WHEN 3002 THEN','WHEN 3004 THEN'])assert.ok(!s.includes(bad),`embedded answer/coupling: ${bad}`);
}
const good=`create or replace package doom_monsters authid definer as procedure advance; end; doom_monster_def join attack_kind pain_chance drop_thing_type doom_state_def join next_state_id state_tics doom_rng_value doom_reject_byte bitand power reject doom_map_linedef doom_map_sidedef game_sessions players mobjs game_events target_mobj_id search breadth first sector_graph sound_reach sound_block visited cycle doom_r1_rays intersect linedef numerator denominator distance order by row_number move_direction collision block radius order by`;
audit(good,'doom_monsters.advance');for(const bad of ['commit;','execute immediate x;','dbms_random.value','when 3001 then x'])assert.throws(()=>audit(`${good} ${bad}`,'doom_monsters.advance'));
if(fs.existsSync(monster)){assert.ok(fs.existsSync(tic),'tic source absent');audit(fs.readFileSync(monster,'utf8'),fs.readFileSync(tic,'utf8'));process.stdout.write('PASS T7.2-SOURCE-AUDIT (relational states, sound graph, REJECT/intercepts, deterministic attacks)\n');}else{assert.notEqual(process.env.T72_REQUIRE_PRODUCTION,'1','T7.2 production missing: sql/sim/060_monsters.sql');process.stdout.write('PASS T7.2-SOURCE-POLICY-SELF-CHECK (production source not yet present)\n');}
