import assert from 'node:assert/strict';import crypto from 'node:crypto';import fs from 'node:fs';import path from 'node:path';
import {applyBatch,canonical,ERR,KEYS,LOGICAL_HZ,MAX_BYTES,normalizeEnvelope,snapshot,stateSha} from './reference.mjs';
const here=import.meta.dirname,root=path.resolve(here,'../..'),load=n=>JSON.parse(fs.readFileSync(path.join(here,n),'utf8'));
const f=load('fixtures.json'),expected=load('expectations.json'),manifest=load('test-ids.json'),mutations=load('mutation-specs.json');let checks=0;
const ok=(v,m)=>{assert.ok(v,m);checks++},eq=(a,b,m)=>{assert.equal(a,b,m);checks++},deep=(a,b,m)=>{assert.deepEqual(a,b,m);checks++};
eq(LOGICAL_HZ,35,'logical Hz');eq(manifest.tests.length,20,'id count');eq(new Set(manifest.tests.map(x=>x.id)).size,20,'unique ids');eq(manifest.tests.reduce((n,x)=>n+x.assertions,0),manifest.declaredAssertions,'assertion sum');eq(manifest.declaredAssertions,430,'declared assertions');
ok(manifest.tests.every(t=>/^T61-[A-Z0-9-]+$/.test(t.id)&&t.intent.length>=90),'stable strong contracts');eq(mutations.mutations.length,18,'mutation count');eq(new Set(mutations.mutations.map(x=>x.id)).size,18,'unique mutations');ok(mutations.mutations.every(m=>manifest.tests.some(t=>t.id===m.killedBy)&&m.change.length>=75&&m.reason.length>=75),'strong mutation contracts');
let s=structuredClone(f.initial);
for(const b of f.batches){const before=structuredClone(s),a=applyBatch(s,b.json),e=expected.scenarios.find(x=>x.name===b.name);s=a.state;eq(s.tic,e.tic,`${b.name} tic`);eq(s.last_command_seq,e.lastSeq,`${b.name} seq`);eq(stateSha(s),e.stateSha,`${b.name} state hash`);eq(s.responses.at(-1).command_sha,e.commandSha,`${b.name} command hash`);eq(a.events.length,e.eventCount,`${b.name} events`);eq(Buffer.from(a.response,'hex').toString(),canonical({v:1,tic:e.tic,logical_hz:35,first_seq:JSON.parse(b.json).commands[0].seq,last_seq:e.lastSeq,command_sha:e.commandSha,state_sha:e.stateSha,event_count:e.eventCount}),`${b.name} payload`);eq(s.tic-before.tic,JSON.parse(b.json).commands.length,`${b.name} one tic per command`)}
deep(s.events.map(e=>[e.tic,e.event_ordinal,e.event_type,e.text_value]),expected.scenarios.find(x=>x.name==='controls').events,'control event order');eq(s.rng_cursor,17,'control stream consumes no RNG');
let r0=applyBatch(structuredClone(f.initial),f.batches[0].json),before=snapshot(r0.state),retry=applyBatch(r0.state,f.batches[0].json);ok(retry.retry,'retry selected cache');eq(retry.response,r0.response,'retry exact bytes');deep(snapshot(retry.state),before,'retry no mutation');
const changed=f.batches[0].json.replace('"forward":1','"forward":0');assert.throws(()=>applyBatch(r0.state,changed),e=>e.code===ERR.CONFLICT);checks++;deep(snapshot(r0.state),before,'conflict leaves caller state');
const advanced=applyBatch(r0.state,f.batches[1].json).state;assert.throws(()=>applyBatch(advanced,f.batches[0].json),e=>e.code===ERR.OLD);checks++;const gap=f.batches[1].json.replace('"seq":2','"seq":4').replace('"seq":3','"seq":5');assert.throws(()=>applyBatch(r0.state,gap),e=>e.code===ERR.GAP);checks++;
const valid=JSON.parse(f.batches[0].json).commands[0],bad=[
 '', '{', '{}', '{"v":2,"commands":[]}', '{"v":1,"commands":[]}', JSON.stringify({v:1,commands:[{...valid,extra:0}]}),
 JSON.stringify({v:1,commands:[Object.fromEntries(KEYS.filter(k=>k!=='fire').map(k=>[k,valid[k]]))]}),JSON.stringify({v:1,commands:[{...valid,turn:0.5}]}),
 JSON.stringify({v:1,commands:[{...valid,run:2}]}),JSON.stringify({v:1,commands:[{...valid,seq:0}]}),JSON.stringify({v:1,commands:Array.from({length:5},(_,i)=>({...valid,seq:i+1}))}),
 JSON.stringify({v:1,commands:[valid,{...valid,seq:3}]}),' '.repeat(MAX_BYTES+1)];
for(const [i,v] of bad.entries()){assert.throws(()=>normalizeEnvelope(v),e=>e.code===ERR.MALFORMED,`bad ${i}`);checks++}
const reordered='{"commands":['+JSON.stringify(valid)+'],"v":1}';deep(normalizeEnvelope(reordered),normalizeEnvelope(f.batches[0].json),'member order canonical');
let split=structuredClone(r0.state),batched=structuredClone(r0.state);const all=JSON.parse(f.batches[1].json).commands;for(const c of all)split=applyBatch(split,JSON.stringify({v:1,commands:[c]})).state;batched=applyBatch(batched,f.batches[1].json).state;eq(stateSha(split),stateSha(batched),'split state hash');deep(split.commands,batched.commands,'split commands');deep(split.events,batched.events,'split events');
const tokenVariant=structuredClone(f.initial);tokenVariant.session_token='ffffffffffffffffffffffffffffffff';eq(stateSha(tokenVariant),stateSha(f.initial),'token excluded');
const shuffled=structuredClone(f.initial);shuffled.mobjs=[{mobj_id:2},{mobj_id:1}];const sorted=structuredClone(shuffled);sorted.mobjs.reverse();eq(stateSha(shuffled),stateSha(sorted),'stable mobj order');
for(const [field,value] of [['skill',4],['current_player_id',1],['rng_cursor',18],['map_status','DONE'],['save_lineage','OTHER']]){const x=structuredClone(f.initial);x[field]=value;ok(stateSha(x)!==stateSha(f.initial),`${field} hash coverage`)}
for(const [field,row] of [['mobjs',{mobj_id:1,state_id:'A'}],['sectors',{sector_id:1,floor_height:0}],['lines',{linedef_id:1,trigger_count:1}],['movers',{mover_id:1,sector_id:1}],['switches',{linedef_id:1,timer_tics:1}]]){const x=structuredClone(f.initial);x[field]=[row];ok(stateSha(x)!==stateSha(f.initial),`${field} hash coverage`)}
const fileSha=p=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex');for(const p of ['evaluator/integrity.json','evaluator/integrity.pending-T5.4.json'])ok(/^[0-9a-f]{64}$/.test(fileSha(p)),`${p} ancestry readable`);
process.stdout.write(`PASS T6.1-EVAL-SELF-CHECK (${checks}/${checks} fixture-contract assertions)\n`);
