import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { deriveRng, directory, loadJson, readPinnedWad, sha256, texturePatches, wadFacts } from './wad-oracle.mjs';

const root = path.resolve(import.meta.dirname, '../..');
const expected = loadJson(path.join(import.meta.dirname, 'expectations.json'));
const tests = loadJson(path.join(import.meta.dirname, 'test-ids.json'));
const mutations = loadJson(path.join(import.meta.dirname, 'mutation-specs.json'));
const archive = path.join(root, 'vendor/freedoom/0.13.0/freedoom-0.13.0.zip');
const wad = readPinnedWad(archive);
const facts = wadFacts(wad);
const names = new Set(directory(wad).map((row) => row.name));
const textures = texturePatches(wad);
const rng = deriveRng();
const sortedNumbers = (values) => [...values].map(Number).sort((a, b) => a - b);

assert.equal(sha256(wad), expected.wadSha256);
assert.equal(facts.marker, 0);
assert.equal(facts.nextMarker, 11);
assert.deepEqual(facts.thingCounts, expected.placedThingCounts);
assert.deepEqual(facts.linedefSpecialCounts, expected.linedefSpecialCounts);
assert.deepEqual(facts.sectorSpecialCounts, expected.sectorSpecialCounts);
assert.deepEqual(facts.wallTextures, expected.wallTextures);
assert.deepEqual(facts.flats, expected.flats);
assert.equal(Object.keys(expected.placedThingCounts).length, 49);
assert.deepEqual(Object.keys(expected.thingIdentities), Object.keys(expected.placedThingCounts));
assert.deepEqual(sortedNumbers(Object.keys(expected.pickupEffects)), sortedNumbers(expected.pickupThingTypes));
assert.equal(expected.wallTextures.length, 114);
assert.equal(expected.flats.length, 44);
assert.ok(expected.wallTextures.every((name) => textures.has(name)));
assert.ok(expected.wallTextures.every((name) => textures.get(name).length > 0));
assert.ok(expected.animationGroups.flatMap((group) => group.frames).every((name) => names.has(name) || textures.has(name)));
assert.ok([...expected.requiredSounds, ...expected.requiredMusic, ...expected.requiredUi].every((name) => names.has(name)));
assert.ok(Object.values(expected.requiredSpritePrefixes).every((prefix) => [...names].some((name) => name.startsWith(prefix))));
assert.equal(rng.length, 256);
assert.equal(sha256(Buffer.from(rng)), expected.rng.sha256);
assert.equal(new Set(rng).size, expected.rng.uniqueValues);
assert.equal(rng.reduce((sum, value) => sum + value, 0), expected.rng.sum);
assert.equal(Math.min(...rng), expected.rng.minimum);
assert.equal(Math.max(...rng), expected.rng.maximum);
assert.equal(tests.tests.length, 16);
assert.equal(new Set(tests.tests.map((test) => test.id)).size, 16);
assert.equal(tests.tests.reduce((sum, test) => sum + test.assertions, 0), 135);
assert.equal(mutations.mutations.length, 12);
assert.ok(mutations.mutations.every((mutation) => tests.tests.some((test) => test.id === mutation.killedBy)));
assert.ok(mutations.mutations.every((mutation) => mutation.change.length > 10));
assert.equal(expected.interactiveMonsterTypes.join(','), '9,58,3001,3002,3004');
assert.deepEqual(Object.keys(expected.linedefSemantics), Object.keys(expected.linedefSpecialCounts));
assert.deepEqual(Object.keys(expected.sectorSemantics), Object.keys(expected.sectorSpecialCounts));
assert.equal(fs.existsSync(path.join(root, 'evaluator/integrity.json')), true);
assert.equal(fs.existsSync(path.join(root, 'evaluator/integrity.pending-T2.2.json')), true);
assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(root, 'evaluator/integrity.json'))).digest('hex'), '2699e0e0f6e93593d8172ea19a048d2ad6ebabb57aef2604a81782c25f2882a3');

process.stdout.write('PASS T2.3-EVAL-SELF-CHECK (36/36 fixture-contract assertions)\n');
