import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';
const root=path.resolve(import.meta.dirname,'../..'),candidate='sql/presentation/090_model_fire.sql';
const strip=s=>s.replace(/\/\*[\s\S]*?\*\//g,' ').replace(/--[^\n]*/g,' ').replace(/'(?:''|[^'])*'/g,"''").toUpperCase();
export function audit(raw){const s=strip(raw),compact=s.replace(/\s+/g,' ');const models=s.match(/\bMODEL\b/g)||[];assert.equal(models.length,1,'production must contain exactly one textual MODEL clause');
 for(const x of ['CREATE TABLE DOOM_FIRE_FRAME_RUN','FRAME_NO','RUN_NO','START_OFFSET','RUN_LENGTH','INTENSITY','CREATE TABLE DOOM_FIRE_BUILD_PROBE','PROBE_ORDINAL','PROBE_NAME','FRAME_COUNT','WIDTH','HEIGHT','CELL_COUNT','ESTIMATED_BYTES','PREINSERT_RUN_COUNT','RESULT_RUN_COUNT','MODEL_OPERATIONS','STATUS','ELAPSED_MS','PGA_BYTES','CREATE OR REPLACE PACKAGE DOOM_FIRE','AUTHID DEFINER','PROCEDURE GENERATE','INSERT INTO DOOM_FIRE_FRAME_RUN','DIMENSION BY','MEASURES','RULES SEQUENTIAL ORDER','CV('])assert.ok(compact.includes(x),`required fire source token absent: ${x}`);
 assert.match(compact,/DIMENSION BY\s*\(\s*FRAME_NO\s*,\s*Y\s*,\s*X\s*\)/,'exact MODEL dimensions/order absent');assert.match(compact,/\][\s\S]{0,200}ORDER BY\s+FRAME_NO\s+ASC\s*,\s*Y\s+DESC\s*,\s*X\s+ASC\s*=/,'dimension ORDER BY absent from rule');
 for(const x of ['150','160','96','2304000','268435456','28','36','256','73','151','199','17','13'])assert.ok(compact.includes(x),`frozen dimension/rule constant absent: ${x}`);
 assert.ok(!/\bMOD\s*\(/.test(s),'Oracle MOD forbidden for wrapped cellular arithmetic');assert.ok(/FLOOR\s*\(/.test(s),'floor modulus/decay implementation absent');assert.ok(!/PROCEDURE\s+GENERATE\s*\([^)]/.test(compact),'public generator dimensions must not be configurable');
 for(const bad of ['DBMS_RANDOM','SYSDATE','SYSTIMESTAMP','CURRENT_TIMESTAMP','SYS_CONTEXT','EXECUTE IMMEDIATE','DBMS_SQL','PRAGMA AUTONOMOUS_TRANSACTION','WHEN OTHERS THEN NULL','EVALUATOR/','EXPECTATIONS.JSON','FIXTURES.JSON','T91-','ADAPTIVE','FALLBACK','JSON_OBJECT','JSON_ARRAY','FRAME_BLOB','CELL_VALUE'])assert.ok(!compact.includes(bad),`forbidden nondeterminism/coupling/fallback/storage: ${bad}`);
 assert.ok(!/\b(COMMIT|ROLLBACK)\b/.test(s),'generator must leave transaction ownership to caller');assert.match(compact,/CHECK\s*\([^)]*RUN_LENGTH\s*>\s*0/,'positive run constraint absent');assert.match(compact,/CHECK\s*\([^)]*INTENSITY\s+BETWEEN\s+0\s+AND\s+36/,'intensity range constraint absent');
}
const valid=`create table doom_fire_frame_run(frame_no number,run_no number,start_offset number,run_length number,intensity number, constraint fr_ck check(run_length>0),constraint fi_ck check(intensity between 0 and 36));create table doom_fire_build_probe(probe_ordinal number,probe_name varchar2(8),frame_count number,width number,height number,cell_count number,estimated_bytes number,preinsert_run_count number,result_run_count number,model_operations number,status varchar2(8),elapsed_ms number,pga_bytes number);create or replace package doom_fire authid definer as procedure generate;end;create or replace package body doom_fire as procedure generate is begin insert into doom_fire_frame_run(frame_no,run_no,start_offset,run_length,intensity) with q as(select frame_no,y,x,heat from dual model dimension by(frame_no,y,x) measures(heat) rules sequential order(heat[frame_no is any,y is any,x is any] order by frame_no asc,y desc,x asc=greatest(0,heat[cv(frame_no)-1,cv(y)+1,cv(x)]-floor((cv(frame_no)*73+cv(x)*151+cv(y)*199+cv(frame_no)*cv(x)*17+cv(x)*cv(y)*13)/256)))) select 150,160,96,2304000,268435456,28,36,256,73,151,199,17,13 from q;end;end;`;
audit(valid);for(const [needle,replacement] of [['model ', ''],['rules sequential order','rules automatic order'],['order by frame_no asc,y desc,x asc=','order by y='],['floor(', 'mod(']])assert.throws(()=>audit(valid.replace(needle,replacement)),`synthetic canary survived: ${needle}`);for(const injected of ['dbms_random','evaluator/'])assert.throws(()=>audit(valid+injected),`synthetic injection survived: ${injected}`);
const file=path.join(root,candidate);if(process.env.T91_REQUIRE_PRODUCTION==='1'){assert.ok(fs.existsSync(file),`${candidate} absent`);audit(fs.readFileSync(file,'utf8'));process.stdout.write(`PASS T9.1-SOURCE-POLICY (${candidate}; one ordered MODEL operation)\n`)}else process.stdout.write(`PASS T9.1-SOURCE-POLICY-SELF-CHECK (synthetic positive and negative canaries; ${fs.existsSync(file)?'production present but intentionally not inspected':'production absent'})\n`);
