import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import {DEFAULTS,canonical,move} from './reference.mjs';
const here=import.meta.dirname,root=path.resolve(here,'../..'),load=n=>JSON.parse(fs.readFileSync(path.join(here,n),'utf8'));
const f=load('fixtures.json'),e=load('expectations.json'),ids=load('test-ids.json'),mut=load('mutation-specs.json');
let checks=0;const ok=(v,m)=>{assert.ok(v,m);checks++},eq=(a,b,m)=>{assert.equal(a,b,m);checks++},deep=(a,b,m)=>{assert.deepEqual(a,b,m);checks++};
eq(ids.tests.length,22,'stable id count');eq(new Set(ids.tests.map(x=>x.id)).size,22,'unique ids');
eq(ids.tests.reduce((n,x)=>n+x.assertions,0),ids.declaredAssertions,'manifest assertion sum');eq(ids.declaredAssertions,372,'declared assertion count');
ok(ids.tests.every(x=>/^T62-[A-Z0-9-]+$/.test(x.id)&&x.intent.length>=80),'meaningful stable ids');
eq(mut.mutations.length,18,'mutation count');eq(new Set(mut.mutations.map(x=>x.id)).size,18,'unique mutations');
ok(mut.mutations.every(x=>ids.tests.some(t=>t.id===x.killedBy)&&x.change.length>=80&&x.reason.length>=80),'complete mutation contracts');
deep(f.constants,DEFAULTS,'reviewed constants');eq(f.scenarios.length,16,'scenario count');eq(e.scenarios.length,16,'expectation coverage');
const got=[];
for(const s of f.scenarios){const result=canonical(move(f.maps[s.map],s.input));got.push({name:s.name,result});deep(result,e.scenarios.find(x=>x.name===s.name).result,`${s.name} independent result`);deep(result,canonical(move(f.maps[s.map],{...s.input})),`${s.name} deterministic`);ok(result.contacts.length<=2,`${s.name} contact bound`);}
eq(crypto.createHash('sha256').update(JSON.stringify(got)).digest('hex'),e.documentSha256,'canonical scenario document');
const byName=new Map(got.map(x=>[x.name,x.result]));
deep(byName.get('head-on').contacts,[{linedefId:10,fraction:.48}],'head-on exact contact');
deep([byName.get('oblique-slide').x,byName.get('oblique-slide').y],[48,30],'oblique tangent slide');
deep(byName.get('corner-two-contact').contacts.map(x=>x.linedefId),[10,11],'corner order');
eq(byName.get('open-portal').contacts.length,0,'open portal admitted');deep([byName.get('valid-step').z,byName.get('valid-step').eyeZ],[24,65],'step and eye');
eq(byName.get('too-high-step').x,48,'high step blocked');eq(byName.get('closed-door').x,48,'closed door blocked');eq(byName.get('low-opening').x,48,'low opening blocked');
eq(byName.get('blocking-flag').contacts[0].linedefId,24,'blocking flag');eq(byName.get('tunneling').contacts[0].fraction,.548,'continuous sweep');
deep([byName.get('noclip').x,byName.get('noclip').contacts.length],[100,0],'noclip bypass');deep([byName.get('noclip-destination').z,byName.get('noclip-destination').destinationSector,byName.get('noclip-destination').eyeZ],[25,1,66],'noclip destination vertical state');eq(byName.get('stable-earliest').contacts[0].linedefId,99,'fraction before id');eq(byName.get('stable-tie').contacts[0].linedefId,7,'id tie');
const shuffled=structuredClone(f.maps.corner);shuffled.lines.reverse();deep(canonical(move(shuffled,f.scenarios.find(x=>x.name==='corner-two-contact').input)),byName.get('corner-two-contact'),'candidate order invariance');
const wall=f.maps.wall,translated=structuredClone(wall);translated.lines=translated.lines.map(l=>({...l,x1:l.x1+337,y1:l.y1-219,x2:l.x2+337,y2:l.y2-219}));
const a=canonical(move(wall,{x:0,y:0,z:0,dx:100,dy:30})),b=canonical(move(translated,{x:337,y:-219,z:0,dx:100,dy:30}));deep([b.x-337,b.y+219,b.contacts], [a.x,a.y,a.contacts],'arbitrary joint translation');
for(const p of ['evaluator/integrity.json','evaluator/integrity.pending-T3.2.json','evaluator/integrity.pending-T3.3.json','evaluator/integrity.pending-T3.4.json'])ok(/^[0-9a-f]{64}$/.test(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex')),`${p} inherited baseline readable`);
process.stdout.write(`PASS T6.2-EVAL-SELF-CHECK (${checks}/${checks} fixture-contract assertions)\n`);
