import {encodedPayload,indices,palette} from './reference.mjs';

const menuPatch=()=>{const bytes=Buffer.alloc(18);bytes.writeInt16LE(1,0);bytes.writeInt16LE(1,2);bytes.writeUInt32LE(12,8);bytes.set([0,1,0,255,0,255],12);return bytes};

export async function fixturePage(page,baseURL){const base=new URL(baseURL),commands=[],requests=[],failures=[];let tic=0,newCalls=0,gestureAudio=[],commandBySeq=new Map;
 await page.addInitScript(()=>{const scheduled=[];class Gain{gain={value:1};connect(){}}class Pan{pan={value:0};connect(){}}class Source{buffer=null;connect(){}start(when=0){scheduled.push(when)}}class AC{state='suspended';currentTime=10;destination={};resume(){this.state='running';return Promise.resolve()}createGain(){return new Gain()}createStereoPanner(){return new Pan()}createBufferSource(){return new Source()}decodeAudioData(){return Promise.resolve({})}}Object.defineProperty(window,'AudioContext',{value:AC});Object.defineProperty(window,'webkitAudioContext',{value:AC});Object.defineProperty(window,'__t102Scheduled',{value:scheduled})});
 page.on('console',m=>{if(m.type()==='error')failures.push(`console:${m.text()}`)});page.on('pageerror',e=>failures.push(`page:${e.message}`));page.on('requestfailed',r=>failures.push(`failed:${r.url()}`));page.on('request',r=>requests.push(`${r.method()} ${r.url()}`));page.on('response',r=>{if(r.status()>=400)failures.push(`http:${r.status()} ${r.url()}`)});
 await page.route('**/ords/doom/doom_api/**',async route=>{const req=route.request(),u=new URL(req.url()),path=u.pathname.toLowerCase(),body=req.postDataJSON?.()??{};if(req.method()!=='POST')return route.fulfill({status:405,body:'POST only'});if(path.endsWith('/get_asset')){const name=body.p_asset_name;if(name==='PLAYPAL')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({p_payload:palette().toString('base64'),p_media_type:'application/octet-stream'})});if(name==='TITLEPIC')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({p_payload:indices(0).toString('base64'),p_media_type:'application/x-doom-indexed'})});return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({p_payload:menuPatch().toString('base64'),p_media_type:'application/x-doom-patch'})})}if(path.endsWith('/new_game')){newCalls++;tic=0;return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({p_session:'0123456789abcdef0123456789abcdef',p_payload:encodedPayload(0)})})}if(path.endsWith('/step')||path.endsWith('/submit_step')){let env;try{env=typeof body.p_commands==='string'?JSON.parse(body.p_commands):body.p_commands}catch{return route.fulfill({status:400,body:'bad commands'})}commands.push(env);const c=env?.commands?.at(-1);if(c)commandBySeq.set(c.seq,c);tic=Math.max(tic,c?.seq??tic+1);if(c?.fire||c?.use)gestureAudio.push(tic);if(path.endsWith('/submit_step'))return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({p_request:(tic.toString(16).padStart(32,'0')).slice(-32)})});return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({p_payload:encodedPayload(tic,{audio:c?.fire?[tic,0,'DSPISTOL',255,128]:null})})})}if(path.endsWith('/poll_frame')){const seq=body.p_seq??1,c=commandBySeq.get(seq);return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({p_ready:1,p_payload:encodedPayload(seq,{audio:c?.fire?[seq,0,"DSPISTOL",255,128]:null})})})}return route.fulfill({status:404,body:'unknown evaluator route'})});
 await page.setViewportSize({width:1280,height:720});await page.goto(base.href,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.querySelector('[data-doom-status]')?.textContent?.includes('press Enter to start'));
 const start=async()=>{await page.keyboard.press('Enter');await page.waitForFunction(()=>document.querySelector('[data-doom-menu] h2')?.textContent==='MAIN MENU');await page.keyboard.press('Enter');await page.waitForFunction(()=>document.querySelector('[data-doom-menu] h2')?.textContent==='CHOOSE SKILL LEVEL');await page.keyboard.press('Enter');await page.waitForFunction(()=>document.querySelector('[data-doom-status]')?.textContent?.includes('pipeline active'))};
 return {commands,requests,failures,gestureAudio,start,get tic(){return tic},get newCalls(){return newCalls},assertClean(){if(failures.length)throw Error(failures.join('\n'));for(const r of requests){const u=r.slice(r.indexOf(' ')+1);if(new URL(u).origin!==base.origin)throw Error(`cross-origin request ${u}`)}}};}
