import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {pathToFileURL} from 'node:url';

const allowed=new Set(['api','input','codec','palette','canvas','audio','patch','presentation-state','main']);
const forbidden=/\b(?:react|preact|vue|svelte|angular|babylon|phaser|pixi|node:|child_process|worker_threads)\b|https?:|data:application\/wasm|eval\s*\(|new\s+Function\s*\(|WebAssembly|Worker\s*\(|SharedWorker|serviceWorker|importScripts|EVALUATOR|PLAYWRIGHT|FIXTURE|GOLDEN|TEST[_-]?ID|REPORTS\//i;
export function auditSources(files){assert.deepEqual([...files.keys()].sort(),[...allowed].sort(),'exact module inventory');for(const [name,text] of files){assert.ok(text.trim().length>=40,`${name} nonempty`);assert.ok(!forbidden.test(text),`${name} forbidden dependency/coupling`);assert.ok(!/@ts-(?:ignore|nocheck|expect-error)|console\.(?:log|debug)|debugger|eslint-disable|TODO|FIXME/.test(text),`${name} suppression/debug lint`);for(const m of text.matchAll(/(?:import|export)\s+(?:[^'";]*?\s+from\s+)?['"]([^'"]+)['"]|import\s*\(\s*['"]([^'"]+)['"]\s*\)/g)){const spec=m[1]||m[2];assert.ok(spec.startsWith('./'),'only local static imports');const base=spec.replace(/^\.\//,'').replace(/\.(?:js|ts)$/,'');assert.ok(allowed.has(base),`allowed import ${spec}`)}assert.ok(!/\b(?:setInterval|requestAnimationFrame)\s*\([^)]*(?:step|simulate|physics|renderWorld)/i.test(text),`${name} no local game loop`) }const api=files.get('api');assert.match(api,/fetch\s*\(/,'API uses fetch');assert.match(api,/\/ords\/doom\/doom_api\//i,'same public API root');const codec=files.get('codec');assert.match(codec,/DecompressionStream\s*\(\s*['"]gzip['"]\s*\)/,'gzip decode');const canvas=files.get('canvas');assert.match(canvas,/putImageData\s*\(/,'canvas byte blit');const input=files.get('input');assert.match(input,/(?:keydown|addEventListener\s*\(\s*['"]keydown)/,'keyboard input');assert.match(input,/(?:pointerdown|touchstart)/,'touch/pointer input');const main=files.get('main');assert.ok(!/(?:innerHTML|insertAdjacentHTML|document\.write)/.test(main),'no markup injection');return true}
export function readProduction(root){const dir=path.join(root,'client/src'),entries=fs.readdirSync(dir,{withFileTypes:true}).filter(x=>x.isFile()&&x.name.endsWith('.ts'));const map=new Map;for(const e of entries){const name=e.name.slice(0,-3);assert.ok(!map.has(name),`duplicate ${name}`);map.set(name,fs.readFileSync(path.join(dir,e.name),'utf8'))}return map}
const synthetic=new Map([
['api',`export const call=()=>fetch('/ords/doom/doom_api/step/');`],['input',`export function bind(){addEventListener('keydown',()=>{});addEventListener('pointerdown',()=>{})}`],['codec',`export const unzip=(b:Blob)=>b.stream().pipeThrough(new DecompressionStream('gzip'));`],['palette',`export const rgb=(p:Uint8Array,c:number)=>[p[c*3],p[c*3+1],p[c*3+2]];`],['canvas',`export const blit=(c:CanvasRenderingContext2D,i:ImageData)=>c.putImageData(i,0,0);`],['audio',`export const sound=(c:AudioContext)=>c.resume();`],['patch',`export const patch=(bytes:Uint8Array)=>new Uint8Array(bytes);`],['presentation-state',`export const state={loading:true,mode:'GAME',muted:false,focused:true,visible:true};`],['main',`import {call} from './api.js'; export const boot=()=>void call();`]
]);
auditSources(synthetic);for(const [file,needle,repl] of [['api','fetch(',`eval('x');fetch(`],['input','addEventListener',`// @ts-ignore\naddEventListener`],['main',"import {call}","import React from 'react'; import {call}"]]){const bad=new Map(synthetic);bad.set(file,bad.get(file).replace(needle,repl));assert.throws(()=>auditSources(bad))}process.stdout.write('PASS T10.2-SOURCE-POLICY-SELF-CHECK (synthetic positive and negative canaries)\n');
if(process.env.T102_REQUIRE_PRODUCTION==='1'){auditSources(readProduction(path.resolve(import.meta.dirname,'../..')));process.stdout.write('PASS T10.2-SOURCE-AUDIT (exact thin-client module and forbidden-import policy)\n')}
