import crypto from 'node:crypto';
export const clone=structuredClone;
export const sha=v=>crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex');
export function pickup(s,type,defs,mutation={}){s=clone(s);const d=defs[type];if(!d)return {state:s,consumed:false};let changed=false;
 if(d.key&&!s.keys.includes(d.key)){s.keys.push(d.key);changed=true} if(d.backpack&&!mutation.noBackpack){for(const k of Object.keys(s.caps))s.caps[k]*=2;changed=true}
 if(d.weapon&&!s.owned.includes(d.weapon)){s.owned.push(d.weapon);changed=true}
 for(const [k,n] of Object.entries(d.ammo||{})){const old=s.ammo[k],cap=s.caps[k];s.ammo[k]=mutation.noCap?old+n:Math.min(cap,old+n);changed||=s.ammo[k]!==old}
 if(d.health){const old=s.health;s.health=Math.min(d.healthCap,s.health+d.health);changed||=old!==s.health} if(d.healthSetMin){const old=s.health;s.health=Math.max(s.health,d.healthSetMin);changed||=old!==s.health}
 if(d.armor){const old=s.armor;s.armor=Math.min(d.armorCap,s.armor+d.armor);changed||=old!==s.armor} if(d.armorSet&&s.armor<d.armorSet){s.armor=d.armorSet;s.armorType=d.armorType;changed=true}
 if(d.power&&!s.powers.includes(d.power)){s.powers.push(d.power);changed=true} if(changed||mutation.consumeAtCap){s.events.push({tic:s.tic,type:'PICKUP',thingType:+type});return {state:s,consumed:true}}return {state:s,consumed:false};}
export function select(s,slot,weapons,mutation={}){s=clone(s);const w=weapons.find(x=>x.slot===slot);if(!w||!s.owned.includes(w.id))return s;const enough=w.ammo==='NONE'||s.ammo[w.ammo]>=w.cost;if(enough||mutation.allowNoAmmo){s.pending=w.id;if(mutation.instantSelect){s.selected=w.id;s.pending=null}else s.weaponState=`WEAPON_${s.selected}_LOWER`}return s;}
const draw=(s,rng)=>{const v=rng[s.rngCursor%rng.length];s.rngCursor=(s.rngCursor+1)%256;return v};
export function fire(s,weapons,rng,mutation={}){s=clone(s);const w=weapons.find(x=>x.id===s.selected);if(!w)return s;const enough=w.ammo==='NONE'||s.ammo[w.ammo]>=w.cost;if(!enough){s.events.push({tic:s.tic,type:'DRY_FIRE'});return s}if(w.ammo!=='NONE')s.ammo[w.ammo]-=w.cost;s.weaponState=`WEAPON_${w.id}_FIRE`;s.flashState=`WEAPON_${w.id}_FLASH`;s.refire++;
 if(w.kind==='HITSCAN'||w.kind==='MELEE'){for(let p=0;p<w.pellets;p++){const spread=mutation.oneRngDraw?0:draw(s,rng)-draw(s,rng);const damage=(draw(s,rng)%3+1)*(w.id==='SHOTGUN'?5:mutation.fixedDamage?5:3);const wall=s.walls.filter(x=>x.blocking).sort((a,b)=>a.distance-b.distance)[0];const target=s.targets.filter(x=>x.solid&&x.health>0).sort((a,b)=>a.x-b.x||a.id-b.id)[0];if(target&&(!wall||target.x<wall.distance)){const hit=mutation.hitFarTarget?s.targets.filter(x=>x.health>0).at(-1):target;hit.health=Math.max(0,hit.health-damage);s.events.push({tic:s.tic,type:'HITSCAN_HIT',target:hit.id,damage,spread})}else s.events.push({tic:s.tic,type:'HITSCAN_MISS',spread});}}
 else{s.projectiles.push({id:s.projectiles.length+1,kind:w.id==='ROCKET_LAUNCHER'?'ROCKET':'PLASMA',x:0,y:0,vx:mutation.zeroVelocity?0:20,owner:0,damage:20});s.events.push({tic:s.tic,type:'PROJECTILE_SPAWN'})}return s;}
export function advanceProjectiles(s,mutation={}){s=clone(s);for(const p of s.projectiles){p.x+=p.vx;const wall=s.walls.find(w=>w.blocking&&p.x>=w.distance);const target=s.targets.filter(t=>t.health>0&&p.x>=t.x).sort((a,b)=>a.x-b.x||a.id-b.id)[0];if(wall&&(!target||wall.distance<=target.x)){p.dead=true;s.events.push({tic:s.tic,type:'PROJECTILE_IMPACT',target:null})}else if(target){target.health=Math.max(0,target.health-p.damage);p.dead=true;s.events.push({tic:s.tic,type:'PROJECTILE_IMPACT',target:target.id})}}s.projectiles=s.projectiles.filter(p=>!p.dead||mutation.keepProjectile);return s;}
export function explode(s,x,y,radius=128,damage=128,mutation={}){s=clone(s);const ids=[...s.targets,...s.barrels].map(v=>v.id).sort((a,b)=>a-b);for(const id of ids){const v=[...s.targets,...s.barrels].find(q=>q.id===id);if(!v||v.barrel&&v.exploded)continue;const dist=Math.hypot(v.x-x,(v.y||0)-y);const wall=s.walls.some(w=>w.blocking&&w.distance>Math.min(x,v.x)&&w.distance<Math.max(x,v.x));if(dist<=radius&&(!wall||mutation.ignoreOcclusion)){const d=Math.max(0,damage-Math.floor(dist));v.health=Math.max(0,v.health-d);if(v.barrel&&v.health===0&&!v.exploded){v.exploded=true;s.events.push({tic:s.tic,type:'BARREL_EXPLODE',target:v.id});if(!mutation.noChain)s=explode(s,v.x,v.y,radius,damage,mutation)}}}return s;}
export const digest=s=>sha({health:s.health,armor:s.armor,ammo:s.ammo,owned:[...s.owned].sort(),selected:s.selected,rngCursor:s.rngCursor,targets:s.targets,barrels:s.barrels,events:s.events});
