import assert from 'node:assert/strict';import fs from 'node:fs';import {advanceProjectiles,digest,explode,fire,pickup,select} from './reference.mjs';
const load=n=>JSON.parse(fs.readFileSync(new URL(n,import.meta.url))),f=load('./fixtures.json'),m=load('./test-ids.json'),mut=load('./mutation-specs.json');let n=0;const eq=(a,b,x)=>{assert.deepEqual(a,b,x);n++},ok=(v,x)=>{assert.ok(v,x);n++},base=()=>structuredClone(f.base);
eq(m.tests.length,23,'test count');eq(new Set(m.tests.map(x=>x.id)).size,23,'unique test IDs');eq(m.tests.reduce((a,x)=>a+x.assertions,0),m.declaredAssertions,'declared sum');eq(m.declaredAssertions,1582,'declared assertion count');ok(m.tests.every(x=>/^T71-[A-Z0-9-]+$/.test(x.id)&&x.intent.length>=110),'strong contracts');eq(mut.mutations.length,22,'mutation count');eq(new Set(mut.mutations.map(x=>x.id)).size,22,'unique mutations');ok(mut.mutations.every(x=>m.tests.some(t=>t.id===x.killedBy)&&x.change.length>=70&&x.reason.length>=75),'focused witnesses documented');
eq(f.e1m1InteractiveTypes.length,23,'reviewed E1M1 interactive distinct types');eq(new Set(f.e1m1InteractiveTypes).size,23,'interactive types unique');ok(f.e1m1InteractiveTypes.every(x=>x===2035||f.pickups[x]),'every E1M1 interactive type covered');eq(f.weapons.length,7,'all weapon definitions');eq(new Set(f.weapons.map(x=>x.slot)).size,7,'unique slots');
for(const type of f.e1m1InteractiveTypes.filter(x=>x!==2035)){const a=pickup(base(),type,f.pickups),b=pickup(base(),type,f.pickups);ok(a.consumed,`E1M1 type ${type} useful focused replay consumes`);eq(a,b,`E1M1 type ${type} focused replay deterministic`)}
let s=base();s.ammo.BULLET=195;let r=pickup(s,2048,f.pickups);eq(r.state.ammo.BULLET,200,'ammo cap');eq(r.consumed,true,'useful consumed');r=pickup(r.state,2048,f.pickups);eq(r.consumed,false,'at cap remains');r=pickup(base(),8,f.pickups);eq(r.state.caps,{BULLET:400,SHELL:100,ROCKET:100,CELL:600},'backpack caps');
s=base();s.owned.push('SHOTGUN');s=select(s,3,f.weapons);eq(s.pending,null,'no-ammo selection rejected');s.ammo.SHELL=2;s=select(s,3,f.weapons);eq(s.pending,'SHOTGUN','owned usable pending');eq(s.weaponState,'WEAPON_PISTOL_LOWER','lower state');
s=base();const dry={...s,ammo:{...s.ammo,BULLET:0}};r=fire(dry,f.weapons,f.rng);eq(r.rngCursor,0,'dry no rng');eq(r.events.at(-1).type,'DRY_FIRE','dry event');eq(r.projectiles.length,0,'dry no attack');
s=fire(base(),f.weapons,f.rng);eq(s.ammo.BULLET,19,'pistol ammo');eq(s.rngCursor,3,'pistol draw count');eq(s.targets[0].health,94,'exact first table damage');eq(s.events[0],{tic:0,type:'HITSCAN_HIT',target:10,damage:6,spread:199},'exact nearest hit');eq(s.flashState,'WEAPON_PISTOL_FLASH','flash state');eq(s.refire,1,'refire count');
let wall=base();wall.walls=[{distance:32,blocking:true}];wall=fire(wall,f.weapons,f.rng);eq(wall.targets[0].health,100,'wall occlusion');eq(wall.events[0].type,'HITSCAN_MISS','blocked miss');
s=base();s.selected='SHOTGUN';s.owned.push('SHOTGUN');s.ammo.SHELL=2;s=fire(s,f.weapons,f.rng);eq(s.ammo.SHELL,1,'shotgun cost');eq(s.events.length,7,'seven pellets');eq(s.rngCursor,21,'three draws each pellet');
s=base();s.selected='ROCKET_LAUNCHER';s.owned.push('ROCKET_LAUNCHER');s.ammo.ROCKET=1;s=fire(s,f.weapons,f.rng);eq(s.projectiles.length,1,'rocket spawned');eq(s.projectiles[0].vx,20,'rocket velocity');eq(s.ammo.ROCKET,0,'rocket spent');s=advanceProjectiles(s);s=advanceProjectiles(s);s=advanceProjectiles(s);s=advanceProjectiles(s);eq(s.targets[0].health,80,'projectile target damage');eq(s.projectiles.length,0,'impact removes projectile');
s=base();s.targets=[{id:1,x:32,y:0,health:100,solid:true},{id:2,x:96,y:0,health:100,solid:true}];s.walls=[{distance:64,blocking:true}];r=explode(s,0,0);eq(r.targets[0].health,4,'near splash');eq(r.targets[1].health,100,'occluded splash');
s=base();s.targets=[];s.barrels=[{id:20,x:0,y:0,health:1,barrel:true},{id:21,x:32,y:0,health:20,barrel:true}];r=explode(s,0,0);eq(r.barrels.every(x=>x.exploded&&x.health===0),true,'barrel chain');eq(r.events.filter(x=>x.type==='BARREL_EXPLODE').length,2,'barrel once events');
s=base();s.health=99;r=pickup(s,2011,f.pickups);eq(r.state.health,100,'stim cap');s=base();s.health=200;r=pickup(s,2014,f.pickups);eq(r.consumed,false,'bonus capped remains');s=base();s.armor=150;s.armorType=2;r=pickup(s,2018,f.pickups);eq([r.state.armor,r.state.armorType,r.consumed],[150,2,false],'weaker armor rejected');r=pickup(base(),5,f.pickups);eq(r.state.keys,['BLUE'],'key state');r=pickup(base(),2023,f.pickups);eq([r.state.health,r.state.powers],[100,['BERSERK']],'berserk state');
const a=fire(base(),f.weapons,f.rng),b=fire(base(),f.weapons,f.rng);eq(digest(a),digest(b),'deterministic replay digest');
process.stdout.write(`PASS T7.1-EVAL-SELF-CHECK (${n}/${n} fixture-contract assertions)\n`);
