import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';
const root=path.resolve(import.meta.dirname,'../..'),combat=path.join(root,'sql/sim/050_combat_inventory.sql'),tic=path.join(root,'sql/sim/tic/010_tic_transaction.sql');
export function audit(c,t){const s=c.toUpperCase(),tx=t.toUpperCase();for(const x of ['CREATE OR REPLACE PACKAGE DOOM_COMBAT','AUTHID DEFINER','PROCEDURE ADVANCE','DOOM_AMMO_DEF','DOOM_WEAPON_DEF','DOOM_PICKUP_DEF','DOOM_PROJECTILE_DEF','DOOM_RNG_VALUE','GAME_SESSIONS','PLAYERS','MOBJS','TIC_COMMANDS','GAME_EVENTS','WEAPON_STATE','FLASH_STATE','REFIRE','RNG_CURSOR','DOOM_R1_RAYS','ORDER BY'])assert.ok(s.includes(x),`required combat token absent: ${x}`);
 assert.ok(tx.includes('DOOM_COMBAT.ADVANCE'),'tic transaction does not delegate combat advancement');
 assert.ok(/DOOM_PICKUP_DEF[\s\S]{0,1000}(JOIN|MERGE)[\s\S]{0,1000}(MOBJS|THING_TYPE)/.test(s),'relational pickup join absent');assert.ok(/DOOM_WEAPON_DEF[\s\S]{0,1200}(JOIN|SELECT)[\s\S]{0,1200}(AMMO|WEAPON_STATE)/.test(s),'relational weapon selection absent');assert.ok(/DOOM_RNG_VALUE[\s\S]{0,900}(RNG_CURSOR|MOD)/.test(s),'ordered database RNG reads absent');assert.ok(/DOOM_R1_RAYS[\s\S]{0,1200}(LINED?EF|INTERSECT|DEPTH|DISTANCE)/.test(s),'reviewed ray/intersection hitscan path absent');assert.ok(/PROJECTILE[\s\S]{0,1400}(MOMENTUM|SWEEP|INTERSECT|COLLISION)/.test(s),'projectile swept collision path absent');assert.ok(/SPLASH[\s\S]{0,1400}(RADIUS|DISTANCE|SQRT)[\s\S]{0,1400}(OCCLUS|BLOCK)/.test(s),'bounded occluded splash path absent');assert.ok(/BARREL[\s\S]{0,1400}(CHAIN|EXPLO)/.test(s),'barrel chain path absent');
 assert.ok(!/\b(COMMIT|ROLLBACK|PRAGMA\s+AUTONOMOUS_TRANSACTION)\b/.test(s),'combat owns transaction boundary');assert.ok(!/EXECUTE\s+IMMEDIATE|DBMS_SQL/.test(s),'dynamic SQL forbidden');assert.ok(!/DBMS_RANDOM|SYSDATE|SYSTIMESTAMP|CURRENT_TIMESTAMP/.test(s),'host random or wall-clock gameplay forbidden');
 for(const bad of ['EVALUATOR/','FIXTURES.JSON','MUTATION-SPECS','REPORTS/','PLAYWRIGHT','CALL_STACK','FORMAT_CALL_STACK','V$PROCESS','T71-','THING_ID IN (','MOBJ_ID IN (','WHEN 87 THEN','WHEN 24 THEN'])assert.ok(!s.includes(bad),`embedded answer/coupling: ${bad}`);
}
const good=`create or replace package doom_combat authid definer as procedure advance; end; doom_ammo_def doom_weapon_def doom_pickup_def doom_projectile_def doom_rng_value game_sessions players mobjs tic_commands game_events weapon_state flash_state refire rng_cursor doom_r1_rays order by doom_pickup_def join mobjs thing_type doom_weapon_def join ammo weapon_state doom_rng_value rng_cursor mod doom_r1_rays linedef intersection distance projectile momentum sweep collision splash radius distance sqrt occlusion blocking barrel chain explosion`;
audit(good,'doom_combat.advance');for(const bad of ['commit;','execute immediate x;','dbms_random.value','when 87 then x','thing_id in (87)'])assert.throws(()=>audit(`${good} ${bad}`,'doom_combat.advance'));
if(fs.existsSync(combat)){assert.ok(fs.existsSync(tic),'tic source absent');audit(fs.readFileSync(combat,'utf8'),fs.readFileSync(tic,'utf8'));process.stdout.write('PASS T7.1-SOURCE-AUDIT (relational inventory, weapons, hitscan, projectiles, splash, barrels)\n');}else{assert.notEqual(process.env.T71_REQUIRE_PRODUCTION,'1','T7.1 production missing: sql/sim/050_combat_inventory.sql');process.stdout.write('PASS T7.1-SOURCE-POLICY-SELF-CHECK (production source not yet present)\n');}
