import assert from 'node:assert/strict';
import crypto from 'node:crypto';
export const sha=x=>crypto.createHash('sha256').update(typeof x==='string'||Buffer.isBuffer(x)?x:JSON.stringify(x)).digest('hex');
const finite=x=>Number.isFinite(x)&&x>=0, hex=x=>/^[0-9a-f]{64}$/.test(x), safePath=x=>/^artifacts\/performance\/t12\.1\/(raw|report)\/[a-z0-9._-]+$/.test(x)&&!x.includes('..');
const percentile=(xs,p)=>xs.slice().sort((a,b)=>a-b)[Math.ceil(p*xs.length)-1];
function scanSecrets(v,f,path='evidence'){
  if(typeof v==='string') for(const p of f.forbiddenSecretPatterns) assert.ok(!v.toLowerCase().includes(p.toLowerCase()),`${path}: forbidden secret pattern ${p}`);
  else if(Array.isArray(v)) v.forEach((x,i)=>scanSecrets(x,f,`${path}[${i}]`));
  else if(v&&typeof v==='object') for(const [k,x] of Object.entries(v)){assert.ok(!/(credential|password|authorization|access.?key|session.?id|bind.?value|endpoint|url)$/i.test(k),`${path}.${k}: secret-bearing key`);scanSecrets(x,f,`${path}.${k}`)}
}
export function makeEvidence(f){
  const samples=Array.from({length:f.frames},(_,frame)=>({frame,phase:frame<f.warmFrames?'warm':'measured',pose:f.poses[frame%f.poses.length],command:f.commands[frame%f.commands.length],externalClock:true,endToEndMs:10+(frame%7),databaseMs:6+(frame%5),ordsMs:1+(frame%3)/10,decodeBlitMs:2+(frame%2)/10,r1Ms:2+(frame%3)/10,r2Ms:3+(frame%4)/10,payloadBytes:9000+(frame%11),payloadSha256:sha(`payload-${frame}`),responseBodyKeys:['frame','width','height','codec','pixels']}));
  const measured=samples.slice(f.warmFrames), vals=k=>measured.map(x=>x[k]);
  const shapes=[]; for(const family of f.statementFamilies) for(const pose of f.poses) for(const command of f.commands) shapes.push({family,pose,command,normalizedShape:`${family.toUpperCase()}(:B1,:B2,:B3)`,forceMatchingSignature:String(100000+f.statementFamilies.indexOf(family)),bindCount:3});
  const plans=f.statementFamilies.map((family,i)=>({family,format:'ALLSTATS LAST',planHashValue:1000+i,executionsBefore:4,executionsAfter:94,operations:[{id:0,operation:'SELECT STATEMENT',starts:90,aRows:90,elapsedUs:10000+i}]}));
  const vsql=f.statementFamilies.map((family,i)=>({family,sqlIdSha256:sha(`sql-${i}`),forceMatchingSignature:String(100000+i),normalizedShape:`${family.toUpperCase()}(:B1,:B2,:B3)`,parseCallsBefore:1,parseCallsAfter:2,executionsBefore:4,executionsAfter:94,versionCount:1}));
  const raw=f.rawKinds.map((kind,i)=>({kind,path:`artifacts/performance/t12.1/raw/${kind}.json`,sha256:sha(`raw-${kind}`),bytes:1000+i,records:kind==='samples'||kind==='payloads'?300:kind==='plans'||kind==='vsql'?3:1}));
  const report={measuredFrames:270,metrics:Object.fromEntries(f.reportMetrics.map(k=>[k,k==='effectiveFps'?{value:1000/(vals('endToEndMs').reduce((a,b)=>a+b,0)/270)}:{p50:percentile(vals(k),.5),p95:percentile(vals(k),.95)}])),cursor:{parseCallsDelta:3,executionsDelta:270,statementFamilies:3},noMinimumThreshold:true,rawManifestSha256:sha(raw)};
  return {schema:1,task:'T12.1',status:'COMPLETE',synthetic:false,resolution:f.resolution,replay:{frames:300,warmFrames:30,measuredFrames:270,sha256:f.replaySha256,commandsSha256:sha(samples.map(x=>x.command))},capture:{owner:'independent evaluator',clock:'external monotonic',startedUtc:'2026-07-15T12:00:00Z',endedUtc:'2026-07-15T12:01:00Z',atomicWrite:true},samples,plans,vsql,shapes,rawArtifacts:raw,reportArtifact:{path:'artifacts/performance/t12.1/report/baseline.json',sha256:sha(report),bytes:4096},report};
}
export function validateEvidence(e,f,{artifactBodies}={}){
  assert.equal(e.schema,1);assert.equal(e.task,'T12.1');assert.equal(e.status,'COMPLETE');assert.equal(e.synthetic,false);assert.deepEqual(e.resolution,f.resolution);
  assert.deepEqual(e.replay,{frames:f.frames,warmFrames:f.warmFrames,measuredFrames:f.measuredFrames,sha256:f.replaySha256,commandsSha256:e.replay.commandsSha256});assert.ok(hex(e.replay.commandsSha256));
  assert.equal(e.capture.owner,'independent evaluator');assert.equal(e.capture.clock,'external monotonic');assert.equal(e.capture.atomicWrite,true);assert.ok(Date.parse(e.capture.endedUtc)>Date.parse(e.capture.startedUtc));
  assert.equal(e.samples.length,300);assert.deepEqual(e.samples.map(x=>x.frame),Array.from({length:300},(_,i)=>i));assert.equal(e.replay.commandsSha256,sha(e.samples.map(x=>x.command)));
  e.samples.forEach((x,i)=>{assert.equal(x.phase,i<30?'warm':'measured');assert.ok(f.poses.includes(x.pose));assert.ok(f.commands.includes(x.command));assert.equal(x.externalClock,true);for(const k of ['endToEndMs','databaseMs','ordsMs','decodeBlitMs','r1Ms','r2Ms','payloadBytes'])assert.ok(finite(x[k]),`frame ${i} ${k}`);assert.ok(hex(x.payloadSha256));assert.ok(f.forbiddenPayloadKeys.every(k=>!x.responseBodyKeys.includes(k)));});
  assert.equal(e.plans.length,3);e.plans.forEach(p=>{assert.ok(f.statementFamilies.includes(p.family));assert.equal(p.format,f.requiredPlanFormat);assert.ok(Number.isInteger(p.planHashValue));assert.ok(p.executionsAfter>p.executionsBefore);assert.ok(p.operations.length&&p.operations.every(o=>Number.isInteger(o.starts)&&Number.isInteger(o.aRows)&&finite(o.elapsedUs)));});
  assert.equal(e.vsql.length,3);e.vsql.forEach(v=>{assert.ok(hex(v.sqlIdSha256));assert.ok(/^\d+$/.test(v.forceMatchingSignature));assert.ok(!/select|update|insert|delete/i.test(v.normalizedShape));assert.ok(v.parseCallsAfter>=v.parseCallsBefore);assert.ok(v.parseCallsAfter-v.parseCallsBefore<=1);assert.equal(v.executionsAfter-v.executionsBefore,90);assert.equal(v.versionCount,1);});
  assert.equal(e.shapes.length,60);for(const family of f.statementFamilies){const a=e.shapes.filter(x=>x.family===family);assert.equal(new Set(a.map(x=>x.normalizedShape)).size,1);assert.equal(new Set(a.map(x=>x.forceMatchingSignature)).size,1);assert.equal(new Set(a.map(x=>x.pose)).size,4);assert.equal(new Set(a.map(x=>x.command)).size,5);}
  const measured=e.samples.slice(30), vals=k=>measured.map(x=>x[k]);assert.equal(e.report.measuredFrames,270);for(const k of f.reportMetrics){assert.ok(e.report.metrics[k]);if(k!=='effectiveFps'){assert.equal(e.report.metrics[k].p50,percentile(vals(k),.5));assert.equal(e.report.metrics[k].p95,percentile(vals(k),.95));}}assert.ok(finite(e.report.metrics.effectiveFps.value));assert.equal(e.report.noMinimumThreshold,true);assert.equal(e.report.cursor.parseCallsDelta,3);assert.equal(e.report.cursor.executionsDelta,270);
  assert.deepEqual(e.rawArtifacts.map(x=>x.kind).sort(),f.rawKinds.slice().sort());e.rawArtifacts.forEach(a=>{assert.ok(safePath(a.path));assert.ok(hex(a.sha256));assert.ok(a.bytes>0&&a.records>0)});assert.equal(e.report.rawManifestSha256,sha(e.rawArtifacts));assert.ok(safePath(e.reportArtifact.path));assert.ok(hex(e.reportArtifact.sha256));assert.ok(e.reportArtifact.bytes>0);assert.equal(e.reportArtifact.sha256,sha(e.report));
  if(artifactBodies){for(const a of [...e.rawArtifacts,e.reportArtifact]){assert.ok(Object.hasOwn(artifactBodies,a.path),`missing artifact ${a.path}`);const b=artifactBodies[a.path];assert.equal(Buffer.byteLength(b),a.bytes,`${a.path} bytes`);assert.equal(sha(b),a.sha256,`${a.path} hash`);scanSecrets(b.toString('utf8'),f,a.path);}}
  scanSecrets(e,f);return true;
}
