import crypto from 'node:crypto';
export const digest=x=>crypto.createHash('sha256').update(typeof x==='string'?x:JSON.stringify(x)).digest('hex');
const keys=['seq','turn','forward','strafe','run','fire','use','weapon','pause','automap','menu','cheat'];
export function expandRoute(route,opt={}){let seq=1,out=[];for(const [runIndex,run] of route.runs.entries()){const repeat=opt.shortenMover&&run.label==='lift-cycle'?Math.max(1,run.repeat-1):run.repeat;for(let i=0;i<repeat;i++){const c={...route.defaults,...run.command,seq:seq++};if(opt.enableCheat&&seq===3)c.cheat='GOD';if(opt.gap&&seq===17)c.seq++;if(opt.injectOutcome)c.complete=1;out.push({runIndex,label:run.label,command:c})}}return out}
export function validateCommands(rows,maxBatch=4){let previous=0;for(const r of rows){const c=r.command;if(JSON.stringify(Object.keys(c).sort())!==JSON.stringify([...keys].sort()))throw Error('command keyset');if(c.seq!==previous+1)throw Error('nonconsecutive sequence');previous=c.seq;for(const k of ['turn','forward','strafe'])if(![-1,0,1].includes(c[k]))throw Error(`range ${k}`);for(const k of ['run','fire','use','pause','automap'])if(![0,1].includes(c[k]))throw Error(`boolean ${k}`);if(!Number.isInteger(c.weapon)||c.weapon<0)throw Error('weapon');if(c.menu!=='NONE'||c.cheat!=='')throw Error('normal-game control');}const batches=[];for(let i=0;i<rows.length;i+=maxBatch)batches.push(rows.slice(i,i+maxBatch).map(x=>x.command));return batches}
export function milestoneSequences(route,rows){const result={};for(const [name,run] of Object.entries(route.milestoneRuns)){const candidates=rows.filter(x=>x.runIndex===run);if(!candidates.length)throw Error(`empty milestone ${name}`);result[name]=run===0?0:candidates.at(-1).command.seq}return result}
export function canonicalScript(rows){return JSON.stringify({v:1,commands:rows.map(x=>x.command)});}
export function compareRuns(a,b,milestones){for(const m of milestones){for(const k of ['tic','seq','stateSha','frameSha','kills','items','secrets','mapStatus','complete'])if(a[m]?.[k]!==b[m]?.[k])throw Error(`${m}.${k} mismatch`)}return true}
export function validateObservation(o,f){if(o.schema!==1||o.map!==f.map||o.skill!==f.skill)throw Error('observation header');if(o.milestones?.length!==f.milestones.length)throw Error('milestone count');for(let i=0;i<f.milestones.length;i++){const m=o.milestones[i];if(m.name!==f.milestones[i])throw Error('milestone order');if(!/^[0-9a-f]{64}$/.test(m.stateSha)||!/^[0-9a-f]{64}$/.test(m.frameSha)||!/^[0-9a-f]{64}$/.test(m.pngSha))throw Error('milestone hash');if(m.width!==320||m.height!==200)throw Error('frame dimensions');if(i&&m.seq<=o.milestones[i-1].seq)throw Error('milestone sequence');}const z=o.final;if(z.complete!==1||z.mapStatus!=='INTERMISSION'||z.kills<f.completion.minimumKills||z.items<f.completion.minimumItems||z.secrets<f.completion.minimumSecrets)throw Error('completion semantics');return true}
