import assert from 'node:assert/strict';import fs from 'node:fs';import {acceptTimeline,emitTransitions,makePresenter} from './reference.mjs';
const load=n=>JSON.parse(fs.readFileSync(new URL(n,import.meta.url))),f=load('./fixtures.json'),m=load('./test-ids.json'),mu=load('./mutation-specs.json');let n=0;const eq=(a,b,x)=>{assert.deepEqual(a,b,x);n++},ok=(v,x)=>{assert.ok(v,x);n++};
eq(m.tests.length,20,'test count');eq(new Set(m.tests.map(x=>x.id)).size,20,'unique ids');eq(m.tests.reduce((a,x)=>a+x.assertions,0),m.declaredAssertions,'declared sum');eq(m.declaredAssertions,684,'declared assertions');ok(m.tests.every(x=>/^T73-[A-Z0-9-]+$/.test(x.id)&&x.intent.length>=110),'strong intents');eq(mu.mutations.length,24,'mutation count');eq(new Set(mu.mutations.map(x=>x.id)).size,24,'unique mutations');ok(mu.mutations.every(x=>m.tests.some(t=>t.id===x.killedBy)&&x.change.length>=70&&x.reason.length>=70),'documented witnesses');
eq(f.definitions.length,9,'reviewed definitions');eq(new Set(f.definitions.map(x=>x.eventType)).size,9,'unique event types');ok(f.definitions.every(x=>['sound','music'].includes(x.kind)&&x.volume>=0&&x.volume<=255&&x.separation>=0&&x.separation<=255),'valid definitions');
const got=emitTransitions(f.transitions,f.definitions).map(x=>[x.tic,x.ordinal,x.asset,x.volume,x.separation]);eq(got,f.expectedTuples,'exact transition timeline');eq(got.filter(x=>x[2]==='D_E1M1').length,1,'music exactly once');eq(got.some(x=>x[2]==='DSPISTOL'),true,'weapon sound');eq(got.some(x=>x[2]==='DSITEMUP'),true,'pickup sound');eq(got.some(x=>x[2]==='DSDOROPN'),true,'door sound');eq(got.some(x=>x[2]==='DSPOSIT1'),true,'wake sound');eq(got.some(x=>x[2]==='DSPODTH1'),true,'death sound');eq(got.some(x=>x[2]==='DSBAREXP'),true,'barrel sound');eq(got.some(x=>x[2]==='DSPLPAIN'),true,'player pain sound');eq(got.some(x=>x[0]===8&&x[2]==='CONTROL_AUTOMAP'),false,'unmapped silent');
for(let i=1;i<got.length;i++)ok(got[i][0]>got[i-1][0]||(got[i][0]===got[i-1][0]&&got[i][1]===got[i-1][1]+1),'strict timeline');
let r=acceptTimeline({last:null},got.slice(0,3));eq(r.accepted.length,3,'accept valid');eq(r.state.last,[7,1],'cursor');assert.throws(()=>acceptTimeline(r.state,[got[2]]),/duplicate/);n++;assert.throws(()=>acceptTimeline(r.state,[got[0]]),/reordered/);n++;for(const bad of [[1,2,'x',3,4],[1,2,'DSOK',256,4],[1,2,'DSOK',3,-1],[1,'2','DSOK',3,4],[1,2,'DSOK',3]]){assert.throws(()=>acceptTimeline({last:null},[bad]));n++}
const calls=[],decoded=[],scheduled=[],ctx={resume:async()=>calls.push('resume'),schedule:(b,x)=>scheduled.push([b,x])};const p=makePresenter({getAsset:async a=>(calls.push(a),`bytes:${a}`),decode:async b=>(decoded.push(b),`decoded:${b}`),context:ctx});await p.consume([[1,0,'DSPISTOL',255,128],[1,1,'DSPISTOL',128,255]]);eq(p.queued,2,'queued before gesture');eq(scheduled.length,0,'no autoplay');eq(calls.filter(x=>x==='DSPISTOL').length,1,'single GET');eq(decoded.length,1,'single decode');await p.enable();eq(p.queued,0,'queue flushed');eq(scheduled.length,2,'two schedules');eq(scheduled[0][1],{volume:1,pan:0,tic:1,ordinal:0},'exact gain pan');eq(scheduled[1][1].volume,128/255,'fractional gain');eq(scheduled[1][1].pan,1,'right pan');p.flush();eq(scheduled.length,2,'no double schedule');
process.stdout.write(`PASS T7.3-EVAL-SELF-CHECK (${n}/${n} fixture-contract assertions)\n`);

