import assert from 'node:assert/strict';import crypto from 'node:crypto';import fs from 'node:fs';import path from 'node:path';import {frameSha,render} from './reference.mjs';
const here=import.meta.dirname,root=path.resolve(here,'../..'),load=n=>JSON.parse(fs.readFileSync(path.join(here,n),'utf8'));
const f=load('fixtures.json'),e=load('expectations.json'),m=load('test-ids.json'),mu=load('mutation-specs.json');let n=0;
const ok=(v,s)=>{assert.ok(v,s);n++},eq=(a,b,s)=>{assert.equal(a,b,s);n++},deep=(a,b,s)=>{assert.deepEqual(a,b,s);n++};
eq(m.tests.length,20,'stable id count');eq(new Set(m.tests.map(x=>x.id)).size,20,'unique ids');eq(m.tests.reduce((a,x)=>a+x.assertions,0),1856885,'assertion sum');eq(m.declaredAssertions,1856885,'declared total');ok(m.tests.every(x=>/^T52-[A-Z0-9-]+$/.test(x.id)&&x.intent.length>75),'strong contracts');
eq(mu.mutations.length,18,'mutation count');eq(new Set(mu.mutations.map(x=>x.id)).size,18,'unique mutations');ok(mu.mutations.every(x=>m.tests.some(t=>t.id===x.killedBy)&&x.change.length>75&&x.reason.length>75),'mutation contract');eq(e.scenes.length,f.scenes.length,'scene coverage');
for(const scene of f.scenes){const r=render(scene,f.animation),w=e.scenes.find(x=>x.name===scene.name);eq(r.pixels.length,64000,`${scene.name} cardinality`);eq(frameSha(r.pixels),w.sha256,`${scene.name} hash`);ok([...r.pixels].every(x=>Number.isInteger(x)&&x>=0&&x<=255),`${scene.name} palette`);eq(new Set(Array.from({length:64000},(_,i)=>`${Math.floor(i/200)}:${i%200}`)).size,64000,`${scene.name} coordinates`);const layers={};for(const x of r.layers)layers[x]=(layers[x]??0)+1;deep(layers,w.layers,`${scene.name} layers`);deep(w.spots.map(([c,y])=>[c,y,r.pixels[c*200+y],r.layers[c*200+y],r.sectors[c*200+y]]),w.spots,`${scene.name} spots`);}
const sky=render(f.scenes.find(x=>x.name==='sky'),f.animation);ok(sky.layers.includes(3),'sky layer absent');const win=render(f.scenes.find(x=>x.name==='window'),f.animation);ok(win.layers.includes(11)&&win.layers.includes(12),'window pieces absent');
const anim=f.scenes.find(x=>x.name==='animation');ok(frameSha(render(anim,f.animation).pixels)!==frameSha(render({...anim,tic:0},f.animation).pixels),'tic animation witness');
const fileSha=p=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex');const inherited=[['evaluator/integrity.pending-T5.1.json','7b02f8ce55c7f67493134cae9c2bc928340fe39b5abfc5457a3dda4c0e5844f7']];for(const [p,h] of inherited)eq(fileSha(p),h,`${p} changed`);const visibleManifest='goldens/integrity-T5.2.json';ok(fileSha(visibleManifest)==='e59b635cdda850ae092d940ac38fb62cbf8e8b2e1ea6812ad67b61a7ebcc4995'&&JSON.parse(fs.readFileSync(path.join(root,visibleManifest),'utf8')).approval.startsWith('HUMAN_REVIEWED_APPROVED'),'reviewed T5.2 visible-golden chain changed');
process.stdout.write(`PASS T5.2-EVAL-SELF-CHECK (${n}/${n} fixture-contract assertions)\n`);
