import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';
const root=path.resolve(import.meta.dirname,'../..'),file=path.join(root,'sql/sim/030_world_machines.sql');assert.ok(fs.existsSync(file),'T6.3 production source missing: sql/sim/030_world_machines.sql');const s=fs.readFileSync(file,'utf8').toUpperCase();
for(const token of ['DOOM_WORLD_MACHINES','ADVANCE','P_SESSION','P_TIC','P_PREVIOUS_X','P_PREVIOUS_Y','GAME_SESSIONS','PLAYERS','TIC_COMMANDS','DOOM_MAP_LINEDEF','DOOM_MAP_VERTEX','DOOM_MAP_SIDEDEF','DOOM_MAP_SECTOR','DOOM_LINEDEF_SPECIAL_DEF','DOOM_SECTOR_SPECIAL_DEF','LINE_STATE','SECTOR_STATE','ACTIVE_MOVERS','ACTIVE_SWITCHES','GAME_EVENTS','DOOM_CONFIG','WORLD_USE_RANGE','WORLD_BUTTON_TICS','WORLD_DOOR_SPEED','WORLD_BLAZE_SPEED','WORLD_DOOR_WAIT','WORLD_LIFT_SPEED','WORLD_LIFT_WAIT','WORLD_DAMAGE_PERIOD','WORLD_DAMAGE_AMOUNT','WORLD_STROBE_BRIGHT','WORLD_STROBE_DARK','BLUE_KEY','SECRET_FOUND','DAMAGE_CLOCK','MAP_STATUS'])assert.ok(s.includes(token),`required world-machine token absent: ${token}`);
for(const n of ['1','2','11','23','26','62','88','117'])assert.ok(new RegExp(`(^|[^0-9])${n}([^0-9]|$)`).test(s),`linedef special ${n} absent`);
for(const n of ['1','7','9','12'])assert.ok(new RegExp(`SPECIAL[^\n]{0,80}(^|[^0-9])${n}([^0-9]|$)`,'m').test(s)||s.includes(`WHEN ${n}`),`sector special ${n} absent`);
assert.ok(/USE_ACTION[\s\S]{0,1200}(64|WORLD_USE_RANGE)/.test(s),'database command use-range path absent');
assert.ok(/(CROSS|PREVIOUS_X)[\s\S]{0,1800}(CROSS|SIDE|DETERMINANT)/.test(s),'exact signed crossing path absent');
assert.ok(/TRIGGER_COUNT[\s\S]{0,1200}(ONCE|REPEAT|SPECIAL)/.test(s),'once/repeat persistence absent');
assert.ok(/BLUE_KEY[\s\S]{0,1000}(DENIED|KEY_DENIED|26)/.test(s),'blue-key denial path absent');
assert.ok(/ACTIVE_SWITCHES[\s\S]{0,1200}(RESTORE_TEXTURE|TIMER_TICS)/.test(s),'button restore machine absent');
assert.ok(/ACTIVE_MOVERS[\s\S]{0,1800}(OCCUP|PLAYER|MOBJS)/.test(s),'mover occupancy path absent');
assert.ok(/MOD\s*\([^,]+,[^)]*(DAMAGE_PERIOD|32)/.test(s),'damage cadence absent');
assert.ok(/SECRET_FOUND[\s\S]{0,800}SECRET_COUNT/.test(s),'secret-once persistence absent');
assert.ok(/RNG_CURSOR[\s\S]{0,1200}DOOM_RNG_VALUE/.test(s),'database random-light sequence absent');
assert.ok(!/\b(COMMIT|ROLLBACK|PRAGMA\s+AUTONOMOUS_TRANSACTION)\b/.test(s),'world machine owns transaction boundary');
assert.ok(!/EXECUTE\s+IMMEDIATE|DBMS_SQL/.test(s),'dynamic SQL forbidden');
const callerAuthored=/\b(?:P_(LINEDEF|SPECIAL|SECTOR|USE_DISTANCE|USE_FRONT|CROSS_DIRECTION|BLUE_KEY)|CALLER_(LINE|SECTOR|KEY))/;
assert.ok(callerAuthored.test('P_LINEDEF')&&callerAuthored.test('CALLER_SECTOR'),'caller-authored trigger policy must reject direct inputs');
assert.ok(!callerAuthored.test('DOOM_MAP_LINEDEF')&&!callerAuthored.test('DOOM_MAP_SECTOR'),'caller-authored trigger policy must allow required map relations');
assert.ok(!callerAuthored.test(s),'caller-authored trigger result forbidden');
for(const bad of ['EVALUATOR/','GOLDENS/','REPORTS/','FIXTURES.JSON','MUTATION-SPECS','PLAYWRIGHT','CALL_STACK','FORMAT_CALL_STACK','V$PROCESS','TEST_NAME','EXPECTED OUTPUT','T63-','101','102','111','123','126','162','188','217'])assert.ok(!s.includes(bad),`embedded evaluator answer or coupling: ${bad}`);
process.stdout.write('PASS T6.3-SOURCE-AUDIT (session-bound relational triggers, machines, hazards, lights, secrets, completion)\n');
