import assert from 'node:assert/strict';import {gunzipJson,sha,validatePayload} from './reference.mjs';
const rawBase=process.env.DOOM_T101_BASE_URL;if(!rawBase)throw Error('DOOM_T101_BASE_URL is required; HTTP acceptance never skips');const base=new URL(rawBase.endsWith('/')?rawBase:`${rawBase}/`);if(base.protocol!=='https:'&&process.env.DOOM_T101_ALLOW_HTTP!=='1')throw Error('HTTPS required unless isolated-local HTTP is explicitly declared');const origin=base.origin;let assertions=0;const ok=(x,m)=>{assert.ok(x,m);assertions++},eq=(a,b,m)=>{assert.deepEqual(a,b,m);assertions++};
function value(o,k){return o?.[k]??o?.[k.toUpperCase()]??o?.items?.[0]?.[k]??o?.items?.[0]?.[k.toUpperCase()]}
async function request(path,{method='POST',body,expect=200}={}){const u=new URL(String(path).replace(/^\//,''),base);eq(u.origin,origin,'same origin');const r=await fetch(u,{method,headers:{'content-type':'application/json','accept':'application/json'},body:body===undefined?undefined:JSON.stringify(body),redirect:'manual'});eq(r.headers.get('location'),null,'redirect forbidden');ok(!['*','null'].includes((r.headers.get('access-control-allow-origin')||'').toLowerCase()),'permissive CORS forbidden');const text=await r.text();if(expect===200)eq(r.status,200,`${method} ${path}: ${text.slice(0,300)}`);else ok(r.status>=400,`${method} ${path} must fail closed`);let json=null;try{json=JSON.parse(text)}catch{}return {r,text,json}}
function blob(o,key='p_payload'){const s=value(o,key);ok(typeof s==='string'&&s.length>2,`${key} base64 absent`);return Buffer.from(s,'base64')}
function payload(o){const bytes=blob(o),{raw,json}=gunzipJson(bytes);ok(raw.length>0,'gzip decompressed');ok(validatePayload(json),'canonical payload contract');eq(Object.keys(json),['v','tic','w','h','mode','state_sha','frame_sha','cols','audio','complete'],'canonical field order');eq(raw.toString('utf8'),JSON.stringify(json),'compact canonical encoding');return {bytes,json}}
const ng=(await request('new_game/',{body:{p_skill:3}})).json,session=value(ng,'p_session'),spawn=payload(ng);ok(/^[0-9a-f]{32}$/.test(session),'128-bit lowercase token');eq(spawn.json.tic,0,'spawn tic');const ng2=(await request('new_game/',{body:{p_skill:3}})).json,session2=value(ng2,'p_session');ok(/^[0-9a-f]{32}$/.test(session2)&&session2!==session,'independent random token');payload(ng2);await request('new_game/',{body:{p_skill:0},expect:'error'});await request('new_game/',{body:{p_skill:6},expect:'error'});
const command=(seq,p={})=>({seq,turn:0,forward:0,strafe:0,run:0,fire:0,use:0,weapon:0,pause:0,automap:0,menu:'NONE',cheat:'',...p});const stepBody=(seq,p={})=>({p_session:session,p_commands:JSON.stringify({v:1,commands:[command(seq,p)]})});
const s1=(await request('step/',{body:stepBody(1,{forward:1})})).json,p1=payload(s1);const retry=(await request('step/',{body:stepBody(1,{forward:1})})).json,pRetry=payload(retry);eq(pRetry.bytes,p1.bytes,'exact retry compressed byte identity');eq(pRetry.json.tic,p1.json.tic,'exact retry no advancement');await request('step/',{body:stepBody(1,{forward:-1}),expect:'error'});await request('step/',{body:stepBody(3),expect:'error'});
for(const commands of [[],Array.from({length:5},(_,i)=>command(i+2)),[{...command(2),turn:.5}],[{...command(2),extra:0}]])await request('step/',{body:{p_session:session,p_commands:JSON.stringify({v:1,commands})},expect:'error'});await request('step/',{body:{p_session:session,p_commands:'x'.repeat(65537)},expect:'error'});const s2=payload((await request('step/',{body:stepBody(2)})).json);eq(s2.json.tic,p1.json.tic+1,'failed requests rolled back');
const concurrentBody=stepBody(3,{turn:1}),both=await Promise.all([request('step/',{body:concurrentBody,expect:'any'}),request('step/',{body:concurrentBody,expect:'any'})]);ok(both.some(x=>x.r.status===200),'one concurrent request succeeds');ok(both.every(x=>x.r.status===200||x.r.status>=400),'second serializes/rejects');const success=both.filter(x=>x.r.status===200).map(x=>payload(x.json));if(success.length===2)eq(success[0].bytes,success[1].bytes,'serialized exact concurrent retry cached');const independent=await Promise.all([request('step/',{body:stepBody(4)}),request('step/',{body:{p_session:session2,p_commands:JSON.stringify({v:1,commands:[command(1)]})}})]);eq(independent.map(x=>x.r.status),[200,200],'independent sessions progress concurrently');independent.forEach(x=>payload(x.json));
const saved=(await request('save_game/',{body:{p_session:session,p_slot:1}})).json,stateSha=value(saved,'p_state_sha');ok(/^[0-9a-f]{64}$/.test(stateSha),'save state sha');payload((await request('load_game/',{body:{p_session:session,p_slot:1}})).json);await request('load_game/',{body:{p_session:session,p_slot:-1},expect:'error'});
const replayStart=(await request('start_replay/',{body:{p_session:session,p_from_tic:0,p_to_tic:1}})).json,replay=value(replayStart,'p_replay_id');ok(typeof replay==='string'&&replay.length>=16,'opaque replay id');payload((await request('step_replay/',{body:{p_replay_id:replay}})).json);await request('start_replay/',{body:{p_session:session,p_from_tic:2,p_to_tic:1},expect:'error'});await request('step_replay/',{body:{p_replay_id:'0'.repeat(32)},expect:'error'});
for(const name of ['PLAYPAL','DSPISTOL']){const a=(await request('get_asset/',{body:{p_asset_name:name}})).json,b=blob(a),media=value(a,'p_media_type');ok(b.length>0,`${name} bytes`);ok(typeof media==='string'&&media.includes('/'),`${name} media type`);eq(sha(b),sha(blob((await request('get_asset/',{body:{p_asset_name:name}})).json)),`${name} deterministic`)}for(const name of ['../PLAYPAL','playpal','PLAYPAL/../X','%2e%2e%2fPLAYPAL','NOT_ALLOWLISTED'])await request('get_asset/',{body:{p_asset_name:name},expect:'error'});
for(const method of ['GET','PUT','PATCH','DELETE'])await request('step/',{method,body:method==='GET'?undefined:stepBody(99),expect:'error'});const schemaBase=new URL('../',base);for(const table of ['game_sessions/','players/','mobjs/','tic_commands/','step_responses/'])await request(new URL(table,schemaBase),{method:'GET',expect:'error'});
const healthUrl=process.env.DOOM_T101_HEALTH_URL;if(!healthUrl)throw Error('DOOM_T101_HEALTH_URL required to prove PUBLIC_HEALTH exposure');const hr=await fetch(healthUrl,{redirect:'manual'});eq(hr.status,200,'health reachable');ok(!['*','null'].includes((hr.headers.get('access-control-allow-origin')||'').toLowerCase()),'health CORS restricted');const health=await hr.text();ok(health.length>0&&!/(password|credential|wallet|token|secret)/i.test(health),'health minimal and secret-free');
process.stdout.write(`PASS T10.1-DIRECT-HTTP (${assertions}/${assertions} raw transport assertions)\n`);
