import assert from 'node:assert/strict';import crypto from 'node:crypto';import fs from 'node:fs';import path from 'node:path';import zlib from 'node:zlib';import {canonical,exactRetryModel,gunzipJson,sha,validateCommandBatch,validatePayload} from './reference.mjs';
const load=n=>JSON.parse(fs.readFileSync(new URL(n,import.meta.url))),f=load('./fixtures.json'),ids=load('./test-ids.json'),m=load('./mutation-specs.json');let n=0;const eq=(a,b,s)=>{assert.deepEqual(a,b,s);n++},ok=(v,s)=>{assert.ok(v,s);n++};
eq(f.procedures.length,7,'seven endpoints');eq(new Set(f.procedures.map(x=>x.toLowerCase())).size,7,'unique public names');eq(Object.keys(f.arguments),f.procedures,'argument fixtures complete');ok(Object.values(f.arguments).every(a=>a.length>=2&&a.every((x,i)=>x.length===3&&['IN','OUT'].includes(x[1]))),'argument direction/type fixtures');eq(f.limits,{requestBytes:65536,maxCommands:4,tokenBytes:16,tokenHexChars:32},'public limits');eq(f.commandKeys.length,12,'command key count');eq(f.errors.length,19,'negative case inventory');eq(new Set(f.errors).size,f.errors.length,'negative cases unique');eq(f.payload.w*f.payload.h,64000,'frame area');
const h=validateCommandBatch(f.validBatch,1,f.commandKeys);ok(/^[0-9a-f]{64}$/.test(h),'canonical command hash');eq(canonical({b:2,a:1}),'{"a":1,"b":2}','canonical object order');for(const bad of [{...f.validBatch,v:2},{v:1,commands:[]},{v:1,commands:Array(5).fill(f.validBatch.commands[0])},{v:1,commands:[{...f.validBatch.commands[0],extra:0}]},{v:1,commands:[{...f.validBatch.commands[0],turn:.5}]},{v:1,commands:[{...f.validBatch.commands[0],seq:2}]}]){assert.throws(()=>validateCommandBatch(bad,1,f.commandKeys));n++}
const cols=Array.from({length:320},(_,x)=>[[0,80,x%256],[80,120,(x+1)%256]]),frame=Buffer.alloc(64000);for(let x=0;x<320;x++){frame.fill(x%256,x*200,x*200+80);frame.fill((x+1)%256,x*200+80,x*200+200)}const payload={v:1,tic:0,w:320,h:200,mode:'GAME',state_sha:'a'.repeat(64),frame_sha:sha(frame),cols,audio:[[0,0,'DSPISTOL',255,128]],complete:0};ok(validatePayload(payload),'payload valid');for(const bad of [{...payload,cols:cols.slice(1)},{...payload,cols:cols.map((c,i)=>i?c:[[0,199,1]])},{...payload,state_sha:'x'},{...payload,extra:1}]){assert.throws(()=>validatePayload(bad));n++}const zipped=zlib.gzipSync(Buffer.from(JSON.stringify(payload))),unz=gunzipJson(zipped);eq(unz.json,payload,'gzip round trip');assert.throws(()=>gunzipJson(Buffer.from('{}')));n++;
const model=exactRetryModel(),a=model(f.validBatch),b=model(f.validBatch);eq(b.cached,true,'retry cached');eq([b.tic,b.events,b.payload],[a.tic,a.events,a.payload],'retry no mutation and byte identity');const conflicting=structuredClone(f.validBatch);conflicting.commands[0].forward=-1;assert.throws(()=>model(conflicting));n++;const next=structuredClone(f.validBatch);next.commands[0].seq=2;eq(model(next).tic,2,'next batch advances');
eq(ids.tests.length,15,'test count');eq(new Set(ids.tests.map(x=>x.id)).size,15,'unique ids');eq(ids.tests.reduce((s,x)=>s+x.assertions,0),ids.declaredAssertions,'assertion sum');ok(ids.tests.every(x=>/^T101-[A-Z0-9-]+$/.test(x.id)&&x.intent.length>=110),'stable strong ids');eq(m.mutations.length,24,'mutation count');eq(new Set(m.mutations.map(x=>x.id)).size,24,'unique mutations');ok(m.mutations.every(x=>ids.tests.some(t=>t.id===x.killedBy)&&x.change.length>=60&&x.reason.length>=75),'mutation witnesses bound');
const root=path.resolve(import.meta.dirname,'../..');for(const p of ['evaluator/integrity.json','evaluator/integrity.pending-T8.2.json'])ok(/^[0-9a-f]{64}$/.test(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex')),`${p} ancestry readable`);eq(sha(Buffer.from(canonical(f.validBatch))),h,'independent digest repeat');
process.stdout.write(`PASS T10.1-EVAL-SELF-CHECK (${n}/${n} fixture-contract assertions)\n`);
