import {test,expect,Page} from '@playwright/test';
import crypto from 'node:crypto';
import {fixturePage} from '../browser-fixture.mjs';
import fixtures from '../fixtures.json' with {type:'json'};

const base=process.env.DOOM_T102_BASE_URL;if(!base)throw Error('DOOM_T102_BASE_URL is required; T10.2 browser acceptance never skips');
const canvas='canvas[data-doom-canvas]';
const hash=async(page:Page)=>page.locator(canvas).evaluate(async(c:HTMLCanvasElement)=>{const b=c.getContext('2d',{willReadFrequently:true})!.getImageData(0,0,320,200).data,h=await crypto.subtle.digest('SHA-256',b);return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')});
async function waitHash(page:Page,value:string){await expect.poll(()=>hash(page),{timeout:8000}).toBe(value)}
const boxesOverlap=(a:any,b:any)=>a.x<b.x+b.width&&a.x+a.width>b.x&&a.y<b.y+b.height&&a.y+a.height>b.y;
async function layout(page:Page,w:number,h:number,name:string){await page.setViewportSize({width:w,height:h});await page.waitForTimeout(50);const c=page.locator(canvas),box=await c.boundingBox();expect(box).not.toBeNull();expect(await c.getAttribute('width')).toBe('320');expect(await c.getAttribute('height')).toBe('200');expect(box!.width/box!.height).toBeCloseTo(1.6,3);expect(box!.x).toBeGreaterThanOrEqual(0);expect(box!.y).toBeGreaterThanOrEqual(0);expect(box!.x+box!.width).toBeLessThanOrEqual(w+.1);expect(box!.y+box!.height).toBeLessThanOrEqual(h+.1);const dims=await page.evaluate(()=>({sw:document.documentElement.scrollWidth,sh:document.documentElement.scrollHeight,cw:document.documentElement.clientWidth,ch:document.documentElement.clientHeight}));expect(dims).toEqual({sw:w,sh:h,cw:w,ch:h});const controls=page.locator('[data-doom-control]:visible'),n=await controls.count(),rects=[];for(let i=0;i<n;i++){const r=await controls.nth(i).boundingBox();expect(r).not.toBeNull();expect(r!.width).toBeGreaterThanOrEqual(40);expect(r!.height).toBeGreaterThanOrEqual(40);expect(boxesOverlap(box,r)).toBe(false);rects.push(r)}for(let i=0;i<rects.length;i++)for(let j=i+1;j<rects.length;j++)expect(boxesOverlap(rects[i],rects[j])).toBe(false);await page.screenshot({path:`/tmp/t10.2-${name}.png`,animations:'disabled'});return n}

test('[T102-IMMEDIATE-CANVAS][T102-CANVAS-HASHES][T102-DESKTOP-LAYOUT][T102-NETWORK-ERROR-GUARDS] immediate deterministic desktop game',async({page},info)=>{info.annotations.push({type:'doom-assertions',description:'259'});const f=await fixturePage(page,base);await expect(page.locator(canvas)).toHaveCount(1);await expect(page.locator(canvas)).toBeVisible();await waitHash(page,fixtures.hashes.rgba0);expect(f.newCalls).toBe(1);expect(await page.locator('main,body').innerText()).not.toMatch(/(?:welcome|learn more|features|pricing|sign up|download|click to start|landing)/i);expect(await page.locator('h1,h2,h3,p,a').count()).toBe(0);expect(await page.locator('video,img,iframe,svg').count()).toBe(0);expect(await layout(page,1280,720,'desktop')).toBe(0);expect((await page.locator(canvas).evaluate((c:any)=>getComputedStyle(c).imageRendering))).toMatch(/pixelated|crisp-edges/);f.assertClean()});

test('[T102-KEYBOARD-WORKFLOW][T102-AUDIO-SCHEDULING][T102-PRESENTATION-STATE] complete keyboard and lifecycle workflow',async({page},info)=>{info.annotations.push({type:'doom-assertions',description:'197'});const f=await fixturePage(page,base);await waitHash(page,fixtures.hashes.rgba0);for(const code of Object.keys(fixtures.keyboard)){const before=f.commands.length;await page.keyboard.down(code);await expect.poll(()=>f.commands.length).toBeGreaterThan(before);await page.keyboard.up(code)}const flat=f.commands.flatMap((x:any)=>x.commands);expect(flat.length).toBeGreaterThanOrEqual(Object.keys(fixtures.keyboard).length);for(let i=0;i<flat.length;i++){expect(Object.keys(flat[i]).sort()).toEqual(['automap','cheat','fire','forward','menu','pause','run','seq','strafe','turn','use','weapon'].sort());expect(Number.isInteger(flat[i].seq)).toBe(true);if(i)expect(flat[i].seq).toBe(flat[i-1].seq+1);for(const k of ['turn','forward','strafe','run','fire','use','weapon','pause','automap'])expect(Number.isInteger(flat[i][k])).toBe(true)}await page.keyboard.down('KeyW');await page.evaluate(()=>window.dispatchEvent(new Event('blur')));const blurStart=f.commands.length;await page.waitForTimeout(120);expect(f.commands.slice(blurStart).flatMap((x:any)=>x.commands).every((x:any)=>x.forward===0)).toBe(true);await page.keyboard.down('KeyD');await page.evaluate(()=>{Object.defineProperty(document,'visibilityState',{configurable:true,value:'hidden'});document.dispatchEvent(new Event('visibilitychange'))});const hidden=f.commands.length;await page.waitForTimeout(120);expect(f.commands.slice(hidden).flatMap((x:any)=>x.commands).every((x:any)=>x.turn===0)).toBe(true);expect(await page.evaluate(()=>(window as any).__t102Scheduled.length)).toBeGreaterThan(0);const beforeMute=await page.evaluate(()=>(window as any).__t102Scheduled.length);await page.keyboard.press('KeyV');await page.keyboard.press('ControlLeft');await page.waitForTimeout(120);expect(await page.evaluate(()=>(window as any).__t102Scheduled.length)).toBe(beforeMute);f.assertClean()});

test('[T102-MOBILE-LAYOUT][T102-TOUCH-WORKFLOW] responsive touch controls',async({page},info)=>{info.annotations.push({type:'doom-assertions',description:'190'});const f=await fixturePage(page,base);await waitHash(page,fixtures.hashes.rgba0);for(const vp of fixtures.viewports.slice(1)){const n=await layout(page,vp.width,vp.height,vp.name);expect(n).toBe(fixtures.semanticControls.length);const names=await page.locator('[data-doom-control]:visible').evaluateAll(es=>es.map(e=>e.getAttribute('data-doom-control')).sort());expect(names).toEqual([...fixtures.semanticControls].sort());for(const el of await page.locator('[data-doom-control]:visible').all()){expect((await el.innerText()).trim()).toBe('');expect(await el.getAttribute('aria-label')).toBeTruthy()}}
 const forward=page.locator('[data-doom-control="forward"]'),fire=page.locator('[data-doom-control="fire"]');const before=f.commands.length;await forward.dispatchEvent('pointerdown',{pointerId:1,pointerType:'touch',isPrimary:true});await fire.dispatchEvent('pointerdown',{pointerId:2,pointerType:'touch',isPrimary:false});await expect.poll(()=>f.commands.length).toBeGreaterThan(before);expect(f.commands.slice(before).flatMap((x:any)=>x.commands).some((x:any)=>x.forward===1&&x.fire===1)).toBe(true);await fire.dispatchEvent('pointerup',{pointerId:2,pointerType:'touch'});await forward.dispatchEvent('pointercancel',{pointerId:1,pointerType:'touch'});const released=f.commands.length;await page.waitForTimeout(120);expect(f.commands.slice(released).flatMap((x:any)=>x.commands).every((x:any)=>x.forward===0&&x.fire===0)).toBe(true);for(const name of ['use','automap','menu','pause','audio']){const n=f.commands.length;await page.locator(`[data-doom-control="${name}"]`).dispatchEvent('pointerdown',{pointerId:7,pointerType:'touch'});await page.locator(`[data-doom-control="${name}"]`).dispatchEvent('pointerup',{pointerId:7,pointerType:'touch'});if(name!=='audio')await expect.poll(()=>f.commands.length).toBeGreaterThan(n)}expect(await page.evaluate(()=>getComputedStyle(document.documentElement).touchAction)).toBe('none');f.assertClean()});

test('[T102-INDEPENDENT-DECODE] malformed transport fails visibly',async({page},info)=>{info.annotations.push({type:'doom-assertions',description:'96'});let served=false;await page.route('**/ords/doom/doom_api/new_game/',async route=>{served=true;await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({p_session:'0123456789abcdef0123456789abcdef',p_payload:'H4sIAAAAAAAA/6tWKkvMKU1VsjKsBQBNJg0NDAAAAA=='})})});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.goto(base);await expect.poll(()=>served).toBe(true);await expect.poll(()=>errors.length).toBeGreaterThan(0);expect(errors.join(' ')).toMatch(/payload|gzip|decode|frame|column|json/i)});
