import assert from 'node:assert/strict';
import crypto from 'node:crypto';
export const sha=x=>crypto.createHash('sha256').update(typeof x==='string'?x:JSON.stringify(x)).digest('hex');
const hex=x=>typeof x==='string'&&/^[0-9a-f]{64}$/.test(x);
const pathIsUnsafe=p=>typeof p!=='string'||p.startsWith('/')||p.includes('..')||p.includes('\\');
const exact=(got,want,label)=>assert.deepEqual([...got].sort(),[...want].sort(),label);
export function validatePolicy(f){
  assert.equal(f.schema,1);assert.equal(f.task,'T11.1');assert.equal(f.deploymentTool.name,'SQLcl');assert.match(f.deploymentTool.version,/^26\.2\.0\.181\.2110$/);
  assert.equal(f.p0Sources.capabilityLocal.sha256,f.p0Sources.capabilityCloud.sha256);for(const x of Object.values(f.p0Sources)){assert.ok(!pathIsUnsafe(x.path));assert.ok(hex(x.sha256));}
  for(const k of ['requiredFeatures','transportCases','scriptDomains','seedDomains','restObjects','directApiCases','forbiddenEvidencePatterns'])assert.ok(Array.isArray(f[k])&&f[k].length>1&&new Set(f[k]).size===f[k].length,k);
  return true;
}
function rows(v,want,label){assert.ok(Array.isArray(v));exact(v.map(x=>x.id),want,label);for(const x of v){assert.equal(x.status,'PASS');assert.ok(Number.isInteger(x.assertions)&&x.assertions>0);assert.ok(hex(x.evidenceSha256));}}
export function validateEvidence(e,f){
  validatePolicy(f);assert.equal(e.schema,1);assert.equal(e.task,'T11.1');assert.equal(e.result,'PASS');assert.equal(e.live,true);assert.equal(e.dryRun,false);assert.equal(e.localSubstitute,false);
  const raw=JSON.stringify(e).toLowerCase();for(const p of f.forbiddenEvidencePatterns)assert.ok(!raw.includes(p),`secret/endpoint pattern ${p}`);assert.ok(!/(skip|not run|todo|placeholder|example\.com|localhost|127\.0\.0\.1)/i.test(raw),'no incomplete/local markers');
  assert.equal(e.target.service,'AUTONOMOUS_DATABASE');assert.ok(Number.isInteger(e.target.databaseMajor)&&e.target.databaseMajor>=f.minimumDatabaseMajor);assert.equal(e.target.managedOrds,true);for(const k of ['targetIdSha256','ordsOriginSha256','databaseQuerySha256','ordsRequestSha256'])assert.ok(hex(e.target[k]),k);assert.notEqual(e.target.targetIdSha256,e.target.ordsOriginSha256);
  assert.equal(e.credentialHygiene.envOnly,true);assert.equal(e.credentialHygiene.filesMode0600,true);assert.equal(e.credentialHygiene.repositorySecretMatches,0);assert.equal(e.credentialHygiene.evidenceSecretMatches,0);assert.equal(e.credentialHygiene.retainedCredentialFiles,0);assert.ok(hex(e.credentialHygiene.scanSha256));
  assert.equal(e.entrance.unchanged,true);assert.deepEqual(e.entrance.sources,f.p0Sources);rows(e.entrance.capabilities,f.requiredFeatures,'capabilities');rows(e.entrance.transport,f.transportCases,'transport');assert.equal(e.entrance.cleanupComplete,true);
  assert.deepEqual(e.deployment.tool,f.deploymentTool);assert.equal(e.deployment.onErrorExit,true);assert.equal(e.deployment.networkInstall,false);assert.equal(e.deployment.retries,0);exact(e.deployment.scripts.map(x=>x.domain),f.scriptDomains,'script domains');for(const x of e.deployment.scripts){assert.ok(Number.isInteger(x.order)&&x.order>0);assert.ok(hex(x.sha256));assert.ok(x.files>0);}assert.deepEqual(e.deployment.scripts.map(x=>x.order),[1,2,3,4]);assert.ok(hex(e.deployment.manifestSha256));
  const r=e.resources;assert.equal(r.observedLive,true);assert.match(r.workload,/^(?:OLTP|APEX|AJD)$/);for(const k of ['cpuCount','storageGb'])assert.ok(Number.isFinite(r[k])&&r[k]>0);assert.equal(typeof r.autoscaling,'boolean');assert.equal(r.withinDeclaredPolicy,true);assert.ok(hex(r.querySha256));
  assert.equal(e.catalog.invalidObjects,0);assert.equal(e.catalog.sqlErrors,0);assert.equal(e.catalog.disabledConstraints,0);assert.equal(e.catalog.unvalidatedConstraints,0);assert.equal(e.catalog.probeObjectsRemaining,0);assert.ok(hex(e.catalog.objectFingerprintSha256));assert.ok(hex(e.catalog.constraintFingerprintSha256));
  exact(e.exposure.restObjects,f.restObjects,'rest objects');assert.equal(e.exposure.customModules,0);assert.equal(e.exposure.customTemplates,0);assert.equal(e.exposure.customHandlers,0);assert.equal(e.exposure.restEnabledTables,0);assert.ok(hex(e.exposure.querySha256));
  exact(e.grants.publicExecute,f.requiredGrantPolicy.publicExecute,'public execute');assert.equal(e.grants.forbiddenSystemPrivilegeCount,0);assert.equal(e.grants.unexpectedGrantCount,0);assert.ok(hex(e.grants.querySha256));
  for(const side of ['local','cloud']){exact(e.seeds[side].map(x=>x.id),f.seedDomains,`${side} seed domains`);for(const x of e.seeds[side]){assert.ok(Number.isInteger(x.count)&&x.count>0);assert.ok(hex(x.sha256));}}const local=new Map(e.seeds.local.map(x=>[x.id,x]));for(const x of e.seeds.cloud)assert.deepEqual(x,local.get(x.id),`seed mismatch ${x.id}`);assert.ok(hex(e.seeds.localMeasurementSha256));assert.ok(hex(e.seeds.cloudMeasurementSha256));
  rows(e.directApi,f.directApiCases,'direct APIs');assert.equal(e.directApi.every(x=>x.originSha256===e.target.ordsOriginSha256),true);assert.equal(e.directApi.every(x=>Number.isInteger(x.httpRequests)&&x.httpRequests>0),true);
  for(const k of ['canonicalEvidenceSha256','deploymentLogSha256','catalogEvidenceSha256','apiEvidenceSha256'])assert.ok(hex(e.provenance[k]),k);assert.equal(e.provenance.atomicWrite,true);assert.equal(e.provenance.secretRedactionPassed,true);return true;
}
export function makeEvidence(f){const obs=ids=>ids.map(id=>({id,status:'PASS',assertions:1,evidenceSha256:sha(id)}));const seeds=f.seedDomains.map((id,i)=>({id,count:i+1,sha256:sha(`seed:${id}`)}));return {schema:1,task:'T11.1',result:'PASS',live:true,dryRun:false,localSubstitute:false,target:{service:'AUTONOMOUS_DATABASE',databaseMajor:23,managedOrds:true,targetIdSha256:sha('target'),ordsOriginSha256:sha('origin'),databaseQuerySha256:sha('db-query'),ordsRequestSha256:sha('ords-request')},credentialHygiene:{envOnly:true,filesMode0600:true,repositorySecretMatches:0,evidenceSecretMatches:0,retainedCredentialFiles:0,scanSha256:sha('scan')},entrance:{unchanged:true,sources:structuredClone(f.p0Sources),capabilities:obs(f.requiredFeatures),transport:obs(f.transportCases),cleanupComplete:true},deployment:{tool:{...f.deploymentTool},onErrorExit:true,networkInstall:false,retries:0,scripts:f.scriptDomains.map((domain,i)=>({domain,order:i+1,sha256:sha(domain),files:i+1})),manifestSha256:sha('manifest')},resources:{observedLive:true,workload:'OLTP',cpuCount:2,storageGb:20,autoscaling:false,withinDeclaredPolicy:true,querySha256:sha('resources')},catalog:{invalidObjects:0,sqlErrors:0,disabledConstraints:0,unvalidatedConstraints:0,probeObjectsRemaining:0,objectFingerprintSha256:sha('objects'),constraintFingerprintSha256:sha('constraints')},exposure:{restObjects:[...f.restObjects],customModules:0,customTemplates:0,customHandlers:0,restEnabledTables:0,querySha256:sha('exposure')},grants:{publicExecute:[...f.requiredGrantPolicy.publicExecute],forbiddenSystemPrivilegeCount:0,unexpectedGrantCount:0,querySha256:sha('grants')},seeds:{local:structuredClone(seeds),cloud:structuredClone(seeds),localMeasurementSha256:sha('local-seeds'),cloudMeasurementSha256:sha('cloud-seeds')},directApi:obs(f.directApiCases).map(x=>({...x,originSha256:sha('origin'),httpRequests:1})),provenance:{canonicalEvidenceSha256:sha('evidence'),deploymentLogSha256:sha('deploy-log'),catalogEvidenceSha256:sha('catalog'),apiEvidenceSha256:sha('api'),atomicWrite:true,secretRedactionPassed:true}}}
