import assert from 'node:assert/strict';
import crypto from 'node:crypto';
export const sha=x=>crypto.createHash('sha256').update(typeof x==='string'||Buffer.isBuffer(x)?x:JSON.stringify(x)).digest('hex');
const finite=x=>Number.isFinite(x)&&x>=0,hex=x=>/^[0-9a-f]{64}$/.test(x),pct=(a,b)=>(a-b)/a*100;
const percentile=(xs,p)=>xs.slice().sort((a,b)=>a-b)[Math.ceil(p*xs.length)-1];
const safePath=x=>/^artifacts\/performance\/t12\.2\/(raw|report)\/[a-z0-9._/-]+$/.test(x)&&!x.includes('..')&&!x.includes('//');
const artifact=(path,tag,kind)=>({kind,path,sha256:sha(tag),bytes:1000+tag.length,records:kind==='samples'?300:1,atomic:true});
const canonical=x=>JSON.stringify(x);
const reportPayload=x=>{const{machineReportSha256,...body}=x;return body};
function scan(v,f,path='evidence'){
  if(typeof v==='string')for(const p of f.forbiddenSecretPatterns)assert.ok(!v.toLowerCase().includes(p.toLowerCase()),`${path}: forbidden ${p}`);
  else if(Array.isArray(v))v.forEach((x,i)=>scan(x,f,`${path}[${i}]`));
  else if(v&&typeof v==='object')for(const[k,x]of Object.entries(v)){assert.ok(!/(credential|password|authorization|access.?key|session.?id|bind.?value|endpoint|url)$/i.test(k),`${path}.${k}: secret-bearing key`);scan(x,f,`${path}.${k}`)}
}
function samples(f,base,tag){return Array.from({length:f.frames},(_,frame)=>({frame,phase:frame<f.warmFrames?'warm':'measured',externalClock:true,endToEndMs:base+(frame%5)*.1,databaseMs:base*.48+(frame%3)*.05,ordsMs:base*.12+(frame%2)*.03,payloadMs:base*.08+(frame%4)*.02,decodeBlitMs:base*.1+(frame%2)*.02,r1Ms:base*.15+(frame%3)*.02,r2Ms:base*.22+(frame%4)*.02,payloadBytes:8200+(frame%7),payloadSha256:sha(`${tag}-${frame}`)}))}
function stats(xs){const m=xs.slice(30),v=k=>m.map(x=>x[k]),mean=v('endToEndMs').reduce((a,b)=>a+b,0)/m.length;return{endToEndMs:{p50:percentile(v('endToEndMs'),.5),p95:percentile(v('endToEndMs'),.95)},effectiveFps:1000/mean,stageMedians:{database:percentile(v('databaseMs'),.5),ords:percentile(v('ordsMs'),.5),payload:percentile(v('payloadMs'),.5),'decode-blit':percentile(v('decodeBlitMs'),.5),r1:percentile(v('r1Ms'),.5),r2:percentile(v('r2Ms'),.5)}}}
const dominant=s=>Object.entries(s.stageMedians).sort((a,b)=>b[1]-a[1])[0][0];
function attemptArtifacts(id,f){return f.requiredRawKinds.map(k=>artifact(`artifacts/performance/t12.2/raw/attempt-${id}/${k}.json`,`${id}-${k}`,k));}
function chainEntry(x,prev){const e={attempt:x.id,startedUtc:x.startedUtc,endedUtc:x.endedUtc,sourceBeforeSha256:x.sourceBeforeSha256,sourceAfterSha256:x.sourceAfterSha256,diffSha256:x.diffSha256,outcome:x.outcome,decision:x.decision,prevEntrySha256:prev};return{...e,entrySha256:sha(e)}}
export function makeEvidence(f){
  const baselineSamples=samples(f,20,'baseline'),baselineStats=stats(baselineSamples),baseline={pinnedManifestSha256:f.ancestry.t12_1,publicSchemaSha256:f.baseline.publicSchemaSha256,goldenManifestSha256:f.baseline.goldenManifestSha256,replaySha256:f.replaySha256,samples:baselineSamples,statistics:baselineStats,selectedRevisionSha256:sha('baseline-revision')};
  const defs=[{id:1,base:16,changeClass:'index',fingerprint:'create-covering-index',decision:'ACCEPTED'},{id:2,base:17,changeClass:'join-order',fingerprint:'leading-join-rewrite',decision:'ROLLED_BACK'},{id:3,base:15.5,changeClass:'precomputed-static-relation',fingerprint:'materialized-static-visibility',decision:'ACCEPTED'}];
  let best=baselineStats.endToEndMs.p50,bestStats=baselineStats,bestRevision=baseline.selectedRevisionSha256;
  const attempts=[];for(const d of defs){const xs=samples(f,d.base,`attempt-${d.id}`),st=stats(xs),imp=pct(best,st.endToEndMs.p50),sourceAfter=sha(`revision-${d.id}`),correctness={passed:true,skipped:false,assertions:120000,expectedAssertions:120000},mutations={passed:true,skipped:false,killed:144,required:144,survivors:[]};correctness.machineReportSha256=sha(canonical(correctness));mutations.machineReportSha256=sha(canonical(mutations));const a={id:d.id,startedUtc:`2026-07-15T12:0${d.id}:00Z`,endedUtc:`2026-07-15T12:0${d.id}:30Z`,changeClass:d.changeClass,changeFingerprint:d.fingerprint,sourceBeforeSha256:bestRevision,sourceAfterSha256:sourceAfter,diffSha256:sha(`diff-${d.id}`),diffNonempty:true,targetBottleneck:dominant(bestStats),profileSourceRevisionSha256:bestRevision,humanReview:{approved:true,targetedMeasuredBottleneck:true,ineffectiveWorkChosenToStop:false,reviewedUtc:`2026-07-15T12:0${d.id}:40Z`,rationale:'The retained runtime profile identifies the named dominant stage and the reviewed diff directly changes its measured execution path.'},samples:xs,statistics:st,bestBeforeP50:best,improvementPercent:imp,outcome:imp<0?'REGRESSION':imp<5?'SUB_FIVE_PERCENT':'IMPROVEMENT',decision:d.decision,publicSchemaSha256:f.baseline.publicSchemaSha256,goldenManifestSha256:f.baseline.goldenManifestSha256,correctness,mutations,artifacts:attemptArtifacts(d.id,f)};const byKind=Object.fromEntries(a.artifacts.map(x=>[x.kind,x]));byKind.samples.sha256=sha(canonical(xs));byKind.diff.sha256=a.diffSha256;byKind.correctness.sha256=a.correctness.machineReportSha256;byKind.mutations.sha256=a.mutations.machineReportSha256;byKind.report.sha256=sha(canonical(st));attempts.push(a);if(d.decision==='ACCEPTED'){best=st.endToEndMs.p50;bestStats=st;bestRevision=sourceAfter}}
  let prev='0'.repeat(64);const journal=attempts.map(a=>{const e=chainEntry(a,prev);prev=e.entrySha256;return e});
  const finalVerification=f.environments.map((environment,i)=>{const xs=samples(f,i?18.5:15.5,`final-${environment}`),a=artifact(`artifacts/performance/t12.2/raw/final-${environment}.json`,`final-${environment}`,'samples');a.sha256=sha(JSON.stringify(xs));return{environment,selectedRevisionSha256:bestRevision,replaySha256:f.replaySha256,samples:xs,statistics:stats(xs),publicSchemaSha256:f.baseline.publicSchemaSha256,goldenManifestSha256:f.baseline.goldenManifestSha256,artifact:a}});
  const report={selectedRevisionSha256:bestRevision,attemptCount:attempts.length,stopAttemptIds:[2,3],stopRule:'TWO_CONSECUTIVE_DISTINCT_ATTEMPTS_BELOW_FIVE_PERCENT',highestVerified:Object.fromEntries(finalVerification.map(v=>[v.environment,{fps:v.statistics.effectiveFps,p50Ms:v.statistics.endToEndMs.p50,p95Ms:v.statistics.endToEndMs.p95,observation:'DIRECT_MEASUREMENT',artifactSha256:v.artifact.sha256}])),marketingEstimate:false,portableThresholdClaim:false,noMinimumThreshold:true};
  const artifacts=[artifact('artifacts/performance/t12.2/raw/journal.json','journal','journal'),artifact('artifacts/performance/t12.2/report/final.json','final-report','report')];artifacts[0].sha256=sha(JSON.stringify(journal));artifacts[1].sha256=sha(JSON.stringify(report));
  const evidence={schema:1,task:'T12.2',status:'COMPLETE',synthetic:false,resolution:f.resolution,replay:{frames:f.frames,warmFrames:f.warmFrames,measuredFrames:f.measuredFrames,sha256:f.replaySha256},capture:{owner:'independent evaluator',clock:'external monotonic',atomicWrite:true,startedUtc:'2026-07-15T12:00:00Z',endedUtc:'2026-07-15T12:10:00Z'},baseline,attempts,journal,finalVerification,artifacts,report};const bodies=makeFixtureArtifactBodies(evidence);for(const a of [...artifacts,...attempts.flatMap(x=>x.artifacts),...finalVerification.map(x=>x.artifact)])a.bytes=Buffer.byteLength(bodies[a.path]);return evidence;
}
export function makeFixtureArtifactBodies(e){const bodies={},put=(a,v)=>{bodies[a.path]=Buffer.from(typeof v==='string'?v:canonical(v))};const root=Object.fromEntries(e.artifacts.map(x=>[x.kind,x]));put(root.journal,e.journal);put(root.report,e.report);for(const a of e.attempts){const k=Object.fromEntries(a.artifacts.map(x=>[x.kind,x]));put(k.samples,a.samples);put(k.diff,`diff-${a.id}`);put(k.correctness,reportPayload(a.correctness));put(k.mutations,reportPayload(a.mutations));put(k.report,a.statistics)}for(const v of e.finalVerification)put(v.artifact,v.samples);return bodies}
function validateSamples(xs,f,label){assert.equal(xs.length,f.frames,`${label} frames`);assert.deepEqual(xs.map(x=>x.frame),Array.from({length:f.frames},(_,i)=>i));xs.forEach((x,i)=>{assert.equal(x.phase,i<f.warmFrames?'warm':'measured');assert.equal(x.externalClock,true);for(const k of['endToEndMs','databaseMs','ordsMs','payloadMs','decodeBlitMs','r1Ms','r2Ms','payloadBytes'])assert.ok(finite(x[k]),`${label} frame ${i} ${k}`);assert.ok(hex(x.payloadSha256))});return stats(xs)}
function validateArtifacts(as,f,expectedKinds){assert.deepEqual(as.map(x=>x.kind).sort(),expectedKinds.slice().sort());for(const a of as){assert.ok(safePath(a.path),a.path);assert.ok(hex(a.sha256));assert.ok(a.bytes>0&&a.records>0);assert.equal(a.atomic,true)}}
export function validateEvidence(e,f,{artifactBodies}={}){
  assert.equal(e.schema,1);assert.equal(e.task,'T12.2');assert.equal(e.status,'COMPLETE');assert.equal(e.synthetic,false);assert.deepEqual(e.resolution,f.resolution);assert.deepEqual(e.replay,{frames:f.frames,warmFrames:f.warmFrames,measuredFrames:f.measuredFrames,sha256:f.replaySha256});
  assert.equal(e.capture.owner,'independent evaluator');assert.equal(e.capture.clock,'external monotonic');assert.equal(e.capture.atomicWrite,true);assert.ok(Date.parse(e.capture.endedUtc)>Date.parse(e.capture.startedUtc));
  assert.equal(e.baseline.pinnedManifestSha256,f.ancestry.t12_1);assert.equal(e.baseline.publicSchemaSha256,f.baseline.publicSchemaSha256);assert.equal(e.baseline.goldenManifestSha256,f.baseline.goldenManifestSha256);assert.equal(e.baseline.replaySha256,f.replaySha256);assert.ok(hex(e.baseline.selectedRevisionSha256));let bestStats=validateSamples(e.baseline.samples,f,'baseline');assert.deepEqual(e.baseline.statistics,bestStats);
  assert.ok(e.attempts.length>=2);assert.deepEqual(e.attempts.map(x=>x.id),Array.from({length:e.attempts.length},(_,i)=>i+1));assert.equal(e.journal.length,e.attempts.length);
  let best=bestStats.endToEndMs.p50,bestRevision=e.baseline.selectedRevisionSha256,prevEntry='0'.repeat(64);const seenDiff=new Set(),seenFingerprint=new Set();
  for(const [i,a] of e.attempts.entries()){
    assert.ok(Date.parse(a.endedUtc)>Date.parse(a.startedUtc));assert.ok(f.allowedChangeClasses.includes(a.changeClass));assert.ok(a.changeFingerprint.length>8&&!seenFingerprint.has(a.changeFingerprint));seenFingerprint.add(a.changeFingerprint);assert.equal(a.sourceBeforeSha256,bestRevision);assert.ok(hex(a.sourceAfterSha256)&&hex(a.diffSha256)&&a.diffNonempty===true&&!seenDiff.has(a.diffSha256));seenDiff.add(a.diffSha256);assert.equal(a.targetBottleneck,dominant(bestStats));assert.equal(a.profileSourceRevisionSha256,bestRevision);
    assert.equal(a.humanReview.approved,true);assert.equal(a.humanReview.targetedMeasuredBottleneck,true);assert.equal(a.humanReview.ineffectiveWorkChosenToStop,false);assert.ok(a.humanReview.rationale.length>80);assert.ok(Date.parse(a.humanReview.reviewedUtc)>=Date.parse(a.endedUtc));
    const st=validateSamples(a.samples,f,`attempt ${a.id}`);assert.deepEqual(a.statistics,st);assert.equal(a.bestBeforeP50,best);const improvement=pct(best,st.endToEndMs.p50);assert.ok(Math.abs(a.improvementPercent-improvement)<1e-9);assert.equal(a.outcome,improvement<0?'REGRESSION':improvement<5?'SUB_FIVE_PERCENT':'IMPROVEMENT');assert.ok(['ACCEPTED','ROLLED_BACK'].includes(a.decision));assert.equal(a.decision,st.endToEndMs.p50<best?'ACCEPTED':'ROLLED_BACK');
    assert.equal(a.publicSchemaSha256,f.baseline.publicSchemaSha256);assert.equal(a.goldenManifestSha256,f.baseline.goldenManifestSha256);assert.deepEqual(a.correctness,{passed:true,skipped:false,assertions:a.correctness.expectedAssertions,expectedAssertions:a.correctness.expectedAssertions,machineReportSha256:a.correctness.machineReportSha256});assert.ok(a.correctness.expectedAssertions>0&&hex(a.correctness.machineReportSha256));assert.equal(a.mutations.passed,true);assert.equal(a.mutations.skipped,false);assert.ok(a.mutations.required>0);assert.equal(a.mutations.killed,a.mutations.required);assert.deepEqual(a.mutations.survivors,[]);assert.ok(hex(a.mutations.machineReportSha256));validateArtifacts(a.artifacts,f,f.requiredRawKinds);const byKind=Object.fromEntries(a.artifacts.map(x=>[x.kind,x]));assert.equal(byKind.samples.sha256,sha(JSON.stringify(a.samples)));assert.equal(byKind.diff.sha256,a.diffSha256);assert.equal(byKind.correctness.sha256,a.correctness.machineReportSha256);assert.equal(byKind.mutations.sha256,a.mutations.machineReportSha256);assert.equal(byKind.report.sha256,sha(JSON.stringify(a.statistics)));
    const j=e.journal[i],expected=chainEntry(a,prevEntry);assert.deepEqual(j,expected);prevEntry=j.entrySha256;if(a.decision==='ACCEPTED'){best=st.endToEndMs.p50;bestStats=st;bestRevision=a.sourceAfterSha256}
  }
  const last=e.attempts.slice(-2);assert.equal(last.length,2);assert.ok(last.every(a=>a.improvementPercent<5));assert.notEqual(last[0].changeClass,last[1].changeClass);assert.notEqual(last[0].changeFingerprint,last[1].changeFingerprint);assert.deepEqual(e.report.stopAttemptIds,last.map(x=>x.id));assert.equal(e.report.stopRule,'TWO_CONSECUTIVE_DISTINCT_ATTEMPTS_BELOW_FIVE_PERCENT');
  assert.deepEqual(e.finalVerification.map(x=>x.environment).sort(),f.environments.slice().sort());for(const v of e.finalVerification){assert.equal(v.selectedRevisionSha256,bestRevision);assert.equal(v.replaySha256,f.replaySha256);assert.equal(v.publicSchemaSha256,f.baseline.publicSchemaSha256);assert.equal(v.goldenManifestSha256,f.baseline.goldenManifestSha256);const st=validateSamples(v.samples,f,`final ${v.environment}`);assert.deepEqual(v.statistics,st);validateArtifacts([v.artifact],f,['samples']);assert.equal(v.artifact.sha256,sha(JSON.stringify(v.samples)));const r=e.report.highestVerified[v.environment];assert.deepEqual(r,{fps:st.effectiveFps,p50Ms:st.endToEndMs.p50,p95Ms:st.endToEndMs.p95,observation:'DIRECT_MEASUREMENT',artifactSha256:v.artifact.sha256})}
  assert.equal(e.report.selectedRevisionSha256,bestRevision);assert.equal(e.report.attemptCount,e.attempts.length);assert.equal(e.report.marketingEstimate,false);assert.equal(e.report.portableThresholdClaim,false);assert.equal(e.report.noMinimumThreshold,true);validateArtifacts(e.artifacts,f,['journal','report']);const rootByKind=Object.fromEntries(e.artifacts.map(x=>[x.kind,x]));assert.equal(rootByKind.journal.sha256,sha(JSON.stringify(e.journal)));assert.equal(rootByKind.report.sha256,sha(JSON.stringify(e.report)));
  const all=[...e.artifacts,...e.attempts.flatMap(a=>a.artifacts),...e.finalVerification.map(v=>v.artifact)];assert.equal(new Set(all.map(a=>a.path)).size,all.length);
  if(artifactBodies){for(const a of all){assert.ok(Object.hasOwn(artifactBodies,a.path),`missing artifact ${a.path}`);const b=artifactBodies[a.path];assert.equal(Buffer.byteLength(b),a.bytes,`${a.path} bytes`);assert.equal(sha(b),a.sha256,`${a.path} hash`);scan(b.toString('utf8'),f,a.path)}const json=a=>JSON.parse(artifactBodies[a.path]);assert.deepEqual(json(rootByKind.journal),e.journal);assert.deepEqual(json(rootByKind.report),e.report);for(const a of e.attempts){const k=Object.fromEntries(a.artifacts.map(x=>[x.kind,x]));assert.deepEqual(json(k.samples),a.samples);assert.deepEqual(json(k.correctness),reportPayload(a.correctness));assert.deepEqual(json(k.mutations),reportPayload(a.mutations));assert.deepEqual(json(k.report),a.statistics)}for(const v of e.finalVerification)assert.deepEqual(json(v.artifact),v.samples)}scan(e,f);return true;
}
